/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Core: THREE.Mesh
    Mesh617: THREE.Mesh
    Mesh617_1: THREE.Mesh
    Mesh616: THREE.Mesh
    Mesh616_1: THREE.Mesh
    Mesh614: THREE.Mesh
    Mesh614_1: THREE.Mesh
    Mesh609: THREE.Mesh
    Mesh609_1: THREE.Mesh
    Mesh606: THREE.Mesh
    Mesh606_1: THREE.Mesh
    Mesh598: THREE.Mesh
    Mesh598_1: THREE.Mesh
    Mesh595: THREE.Mesh
    Mesh595_1: THREE.Mesh
    Mesh592: THREE.Mesh
    Mesh592_1: THREE.Mesh
    Mesh590: THREE.Mesh
    Mesh590_1: THREE.Mesh
    Mesh589: THREE.Mesh
    Mesh589_1: THREE.Mesh
    Mesh588: THREE.Mesh
    Mesh588_1: THREE.Mesh
    Mesh582: THREE.Mesh
    Mesh582_1: THREE.Mesh
    Mesh580: THREE.Mesh
    Mesh580_1: THREE.Mesh
    Mesh579: THREE.Mesh
    Mesh579_1: THREE.Mesh
    Mesh578: THREE.Mesh
    Mesh578_1: THREE.Mesh
    Mesh576: THREE.Mesh
    Mesh576_1: THREE.Mesh
    Mesh574: THREE.Mesh
    Mesh574_1: THREE.Mesh
    Mesh570: THREE.Mesh
    Mesh570_1: THREE.Mesh
    Mesh567: THREE.Mesh
    Mesh567_1: THREE.Mesh
    Mesh565: THREE.Mesh
    Mesh565_1: THREE.Mesh
    Mesh559: THREE.Mesh
    Mesh559_1: THREE.Mesh
    Mesh558: THREE.Mesh
    Mesh558_1: THREE.Mesh
    Mesh557: THREE.Mesh
    Mesh557_1: THREE.Mesh
    Mesh555: THREE.Mesh
    Mesh555_1: THREE.Mesh
    Mesh551: THREE.Mesh
    Mesh551_1: THREE.Mesh
    Mesh548: THREE.Mesh
    Mesh548_1: THREE.Mesh
    Mesh547: THREE.Mesh
    Mesh547_1: THREE.Mesh
    Mesh542: THREE.Mesh
    Mesh542_1: THREE.Mesh
    Mesh541: THREE.Mesh
    Mesh541_1: THREE.Mesh
    Mesh535: THREE.Mesh
    Mesh535_1: THREE.Mesh
    Mesh533: THREE.Mesh
    Mesh533_1: THREE.Mesh
    Mesh530: THREE.Mesh
    Mesh530_1: THREE.Mesh
    Mesh527: THREE.Mesh
    Mesh527_1: THREE.Mesh
    Mesh526: THREE.Mesh
    Mesh526_1: THREE.Mesh
    Mesh514: THREE.Mesh
    Mesh514_1: THREE.Mesh
    Mesh512: THREE.Mesh
    Mesh512_1: THREE.Mesh
    Mesh506: THREE.Mesh
    Mesh506_1: THREE.Mesh
    Mesh501: THREE.Mesh
    Mesh501_1: THREE.Mesh
    Mesh499: THREE.Mesh
    Mesh499_1: THREE.Mesh
    Mesh497: THREE.Mesh
    Mesh497_1: THREE.Mesh
    Mesh493: THREE.Mesh
    Mesh493_1: THREE.Mesh
    Mesh491: THREE.Mesh
    Mesh491_1: THREE.Mesh
    Mesh489: THREE.Mesh
    Mesh489_1: THREE.Mesh
    Mesh487: THREE.Mesh
    Mesh487_1: THREE.Mesh
    Mesh486: THREE.Mesh
    Mesh486_1: THREE.Mesh
    Mesh484: THREE.Mesh
    Mesh484_1: THREE.Mesh
    Mesh476: THREE.Mesh
    Mesh476_1: THREE.Mesh
    Mesh475: THREE.Mesh
    Mesh475_1: THREE.Mesh
    Mesh467: THREE.Mesh
    Mesh467_1: THREE.Mesh
    Mesh463: THREE.Mesh
    Mesh463_1: THREE.Mesh
    Mesh462: THREE.Mesh
    Mesh462_1: THREE.Mesh
    Mesh458: THREE.Mesh
    Mesh458_1: THREE.Mesh
    Mesh457: THREE.Mesh
    Mesh457_1: THREE.Mesh
    Mesh455: THREE.Mesh
    Mesh455_1: THREE.Mesh
    Mesh454: THREE.Mesh
    Mesh454_1: THREE.Mesh
    Mesh453: THREE.Mesh
    Mesh453_1: THREE.Mesh
    Mesh452: THREE.Mesh
    Mesh452_1: THREE.Mesh
    Mesh451: THREE.Mesh
    Mesh451_1: THREE.Mesh
    Mesh450: THREE.Mesh
    Mesh450_1: THREE.Mesh
    Mesh448: THREE.Mesh
    Mesh448_1: THREE.Mesh
    Mesh447: THREE.Mesh
    Mesh447_1: THREE.Mesh
    Mesh446: THREE.Mesh
    Mesh446_1: THREE.Mesh
    Mesh443: THREE.Mesh
    Mesh443_1: THREE.Mesh
    Mesh442: THREE.Mesh
    Mesh442_1: THREE.Mesh
    Mesh439: THREE.Mesh
    Mesh439_1: THREE.Mesh
    Mesh437: THREE.Mesh
    Mesh437_1: THREE.Mesh
    Mesh436: THREE.Mesh
    Mesh436_1: THREE.Mesh
    Mesh435: THREE.Mesh
    Mesh435_1: THREE.Mesh
    Mesh432: THREE.Mesh
    Mesh432_1: THREE.Mesh
    Mesh427: THREE.Mesh
    Mesh427_1: THREE.Mesh
    Mesh426: THREE.Mesh
    Mesh426_1: THREE.Mesh
    Mesh423: THREE.Mesh
    Mesh423_1: THREE.Mesh
    Mesh422: THREE.Mesh
    Mesh422_1: THREE.Mesh
    Mesh421: THREE.Mesh
    Mesh421_1: THREE.Mesh
    Mesh418: THREE.Mesh
    Mesh418_1: THREE.Mesh
    Mesh413: THREE.Mesh
    Mesh413_1: THREE.Mesh
    Mesh412: THREE.Mesh
    Mesh412_1: THREE.Mesh
    Mesh411: THREE.Mesh
    Mesh411_1: THREE.Mesh
    Mesh225: THREE.Mesh
    Mesh225_1: THREE.Mesh
    Mesh615: THREE.Mesh
    Mesh615_1: THREE.Mesh
    Mesh613: THREE.Mesh
    Mesh613_1: THREE.Mesh
    Mesh612: THREE.Mesh
    Mesh612_1: THREE.Mesh
    Mesh611: THREE.Mesh
    Mesh611_1: THREE.Mesh
    Mesh610: THREE.Mesh
    Mesh610_1: THREE.Mesh
    Mesh608: THREE.Mesh
    Mesh608_1: THREE.Mesh
    Mesh607: THREE.Mesh
    Mesh607_1: THREE.Mesh
    Mesh605: THREE.Mesh
    Mesh605_1: THREE.Mesh
    Mesh604: THREE.Mesh
    Mesh604_1: THREE.Mesh
    Mesh603: THREE.Mesh
    Mesh603_1: THREE.Mesh
    Mesh602: THREE.Mesh
    Mesh602_1: THREE.Mesh
    Mesh601: THREE.Mesh
    Mesh601_1: THREE.Mesh
    Mesh600: THREE.Mesh
    Mesh600_1: THREE.Mesh
    Mesh599: THREE.Mesh
    Mesh599_1: THREE.Mesh
    Mesh597: THREE.Mesh
    Mesh597_1: THREE.Mesh
    Mesh596: THREE.Mesh
    Mesh596_1: THREE.Mesh
    Mesh594: THREE.Mesh
    Mesh594_1: THREE.Mesh
    Mesh593: THREE.Mesh
    Mesh593_1: THREE.Mesh
    Mesh591: THREE.Mesh
    Mesh591_1: THREE.Mesh
    Mesh587: THREE.Mesh
    Mesh587_1: THREE.Mesh
    Mesh586: THREE.Mesh
    Mesh586_1: THREE.Mesh
    Mesh585: THREE.Mesh
    Mesh585_1: THREE.Mesh
    Mesh584: THREE.Mesh
    Mesh584_1: THREE.Mesh
    Mesh583: THREE.Mesh
    Mesh583_1: THREE.Mesh
    Mesh581: THREE.Mesh
    Mesh581_1: THREE.Mesh
    Mesh577: THREE.Mesh
    Mesh577_1: THREE.Mesh
    Mesh575: THREE.Mesh
    Mesh575_1: THREE.Mesh
    Mesh573: THREE.Mesh
    Mesh573_1: THREE.Mesh
    Mesh572: THREE.Mesh
    Mesh572_1: THREE.Mesh
    Mesh571: THREE.Mesh
    Mesh571_1: THREE.Mesh
    Mesh569: THREE.Mesh
    Mesh569_1: THREE.Mesh
    Mesh568: THREE.Mesh
    Mesh568_1: THREE.Mesh
    Mesh566: THREE.Mesh
    Mesh566_1: THREE.Mesh
    Mesh564: THREE.Mesh
    Mesh564_1: THREE.Mesh
    Mesh563: THREE.Mesh
    Mesh563_1: THREE.Mesh
    Mesh562: THREE.Mesh
    Mesh562_1: THREE.Mesh
    Mesh561: THREE.Mesh
    Mesh561_1: THREE.Mesh
    Mesh560: THREE.Mesh
    Mesh560_1: THREE.Mesh
    Mesh556: THREE.Mesh
    Mesh556_1: THREE.Mesh
    Mesh554: THREE.Mesh
    Mesh554_1: THREE.Mesh
    Mesh553: THREE.Mesh
    Mesh553_1: THREE.Mesh
    Mesh552: THREE.Mesh
    Mesh552_1: THREE.Mesh
    Mesh550: THREE.Mesh
    Mesh550_1: THREE.Mesh
    Mesh549: THREE.Mesh
    Mesh549_1: THREE.Mesh
    Mesh546: THREE.Mesh
    Mesh546_1: THREE.Mesh
    Mesh545: THREE.Mesh
    Mesh545_1: THREE.Mesh
    Mesh544: THREE.Mesh
    Mesh544_1: THREE.Mesh
    Mesh543: THREE.Mesh
    Mesh543_1: THREE.Mesh
    Mesh540: THREE.Mesh
    Mesh540_1: THREE.Mesh
    Mesh539: THREE.Mesh
    Mesh539_1: THREE.Mesh
    Mesh538: THREE.Mesh
    Mesh538_1: THREE.Mesh
    Mesh537: THREE.Mesh
    Mesh537_1: THREE.Mesh
    Mesh536: THREE.Mesh
    Mesh536_1: THREE.Mesh
    Mesh534: THREE.Mesh
    Mesh534_1: THREE.Mesh
    Mesh532: THREE.Mesh
    Mesh532_1: THREE.Mesh
    Mesh531: THREE.Mesh
    Mesh531_1: THREE.Mesh
    Mesh529: THREE.Mesh
    Mesh529_1: THREE.Mesh
    Mesh528: THREE.Mesh
    Mesh528_1: THREE.Mesh
    Mesh525: THREE.Mesh
    Mesh525_1: THREE.Mesh
    Mesh524: THREE.Mesh
    Mesh524_1: THREE.Mesh
    Mesh523: THREE.Mesh
    Mesh523_1: THREE.Mesh
    Mesh522: THREE.Mesh
    Mesh522_1: THREE.Mesh
    Mesh521: THREE.Mesh
    Mesh521_1: THREE.Mesh
    Mesh520: THREE.Mesh
    Mesh520_1: THREE.Mesh
    Mesh519: THREE.Mesh
    Mesh519_1: THREE.Mesh
    Mesh518: THREE.Mesh
    Mesh518_1: THREE.Mesh
    Mesh517: THREE.Mesh
    Mesh517_1: THREE.Mesh
    Mesh516: THREE.Mesh
    Mesh516_1: THREE.Mesh
    Mesh515: THREE.Mesh
    Mesh515_1: THREE.Mesh
    Mesh513: THREE.Mesh
    Mesh513_1: THREE.Mesh
    Mesh511: THREE.Mesh
    Mesh511_1: THREE.Mesh
    Mesh510: THREE.Mesh
    Mesh510_1: THREE.Mesh
    Mesh509: THREE.Mesh
    Mesh509_1: THREE.Mesh
    Mesh508: THREE.Mesh
    Mesh508_1: THREE.Mesh
    Mesh507: THREE.Mesh
    Mesh507_1: THREE.Mesh
    Mesh505: THREE.Mesh
    Mesh505_1: THREE.Mesh
    Mesh504: THREE.Mesh
    Mesh504_1: THREE.Mesh
    Mesh503: THREE.Mesh
    Mesh503_1: THREE.Mesh
    Mesh502: THREE.Mesh
    Mesh502_1: THREE.Mesh
    Mesh500: THREE.Mesh
    Mesh500_1: THREE.Mesh
    Mesh498: THREE.Mesh
    Mesh498_1: THREE.Mesh
    Mesh496: THREE.Mesh
    Mesh496_1: THREE.Mesh
    Mesh495: THREE.Mesh
    Mesh495_1: THREE.Mesh
    Mesh494: THREE.Mesh
    Mesh494_1: THREE.Mesh
    Mesh492: THREE.Mesh
    Mesh492_1: THREE.Mesh
    Mesh490: THREE.Mesh
    Mesh490_1: THREE.Mesh
    Mesh488: THREE.Mesh
    Mesh488_1: THREE.Mesh
    Mesh485: THREE.Mesh
    Mesh485_1: THREE.Mesh
    Mesh483: THREE.Mesh
    Mesh483_1: THREE.Mesh
    Mesh482: THREE.Mesh
    Mesh482_1: THREE.Mesh
    Mesh481: THREE.Mesh
    Mesh481_1: THREE.Mesh
    Mesh480: THREE.Mesh
    Mesh480_1: THREE.Mesh
    Mesh479: THREE.Mesh
    Mesh479_1: THREE.Mesh
    Mesh478: THREE.Mesh
    Mesh478_1: THREE.Mesh
    Mesh477: THREE.Mesh
    Mesh477_1: THREE.Mesh
    Mesh474: THREE.Mesh
    Mesh474_1: THREE.Mesh
    Mesh473: THREE.Mesh
    Mesh473_1: THREE.Mesh
    Mesh472: THREE.Mesh
    Mesh472_1: THREE.Mesh
    Mesh471: THREE.Mesh
    Mesh471_1: THREE.Mesh
    Mesh470: THREE.Mesh
    Mesh470_1: THREE.Mesh
    Mesh469: THREE.Mesh
    Mesh469_1: THREE.Mesh
    Mesh468: THREE.Mesh
    Mesh468_1: THREE.Mesh
    Mesh466: THREE.Mesh
    Mesh466_1: THREE.Mesh
    Mesh465: THREE.Mesh
    Mesh465_1: THREE.Mesh
    Mesh464: THREE.Mesh
    Mesh464_1: THREE.Mesh
    Mesh461: THREE.Mesh
    Mesh461_1: THREE.Mesh
    Mesh460: THREE.Mesh
    Mesh460_1: THREE.Mesh
    Mesh459: THREE.Mesh
    Mesh459_1: THREE.Mesh
    Mesh456: THREE.Mesh
    Mesh456_1: THREE.Mesh
    Mesh449: THREE.Mesh
    Mesh449_1: THREE.Mesh
    Mesh445: THREE.Mesh
    Mesh445_1: THREE.Mesh
    Mesh444: THREE.Mesh
    Mesh444_1: THREE.Mesh
    Mesh441: THREE.Mesh
    Mesh441_1: THREE.Mesh
    Mesh440: THREE.Mesh
    Mesh440_1: THREE.Mesh
    Mesh438: THREE.Mesh
    Mesh438_1: THREE.Mesh
    Mesh434: THREE.Mesh
    Mesh434_1: THREE.Mesh
    Mesh433: THREE.Mesh
    Mesh433_1: THREE.Mesh
    Mesh431: THREE.Mesh
    Mesh431_1: THREE.Mesh
    Mesh430: THREE.Mesh
    Mesh430_1: THREE.Mesh
    Mesh429: THREE.Mesh
    Mesh429_1: THREE.Mesh
    Mesh428: THREE.Mesh
    Mesh428_1: THREE.Mesh
    Mesh425: THREE.Mesh
    Mesh425_1: THREE.Mesh
    Mesh424: THREE.Mesh
    Mesh424_1: THREE.Mesh
    Mesh420: THREE.Mesh
    Mesh420_1: THREE.Mesh
    Mesh419: THREE.Mesh
    Mesh419_1: THREE.Mesh
    Mesh417: THREE.Mesh
    Mesh417_1: THREE.Mesh
    Mesh416: THREE.Mesh
    Mesh416_1: THREE.Mesh
    Mesh415: THREE.Mesh
    Mesh415_1: THREE.Mesh
    Mesh414: THREE.Mesh
    Mesh414_1: THREE.Mesh
    Mesh410: THREE.Mesh
    Mesh410_1: THREE.Mesh
    Mesh409: THREE.Mesh
    Mesh409_1: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://dqeczc7c9n9n1.cloudfront.net/models/moltenPlanet-1665448576/moltenPlanet.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const {nodes, materials} = useGLTF(FILE_URL) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={75} position={[-10, -10, -100]}>
        <group name="Cube001" scale={[2, 0.4, 2]}/>
        <group name="Camera" position={[0.0734, 0.0054, 4.4711]} rotation={[Math.PI / 2, -Math.PI / 9, 0]}/>
        <mesh name="Core" geometry={nodes.Core.geometry} material={materials['Material.003']}/>
        <group name="Sphere_cell080_cell209" position={[0.9226, -0.0126, 0.6969]}>
          <mesh name="Mesh617" geometry={nodes.Mesh617.geometry} material={nodes.Mesh617.material}/>
          <mesh name="Mesh617_1" geometry={nodes.Mesh617_1.geometry} material={nodes.Mesh617_1.material}/>
        </group>
        <group name="Sphere_cell080_cell208" position={[0.8444, 0.1115, 0.7773]}>
          <mesh name="Mesh616" geometry={nodes.Mesh616.geometry} material={nodes.Mesh616.material}/>
          <mesh name="Mesh616_1" geometry={nodes.Mesh616_1.geometry} material={nodes.Mesh616_1.material}/>
        </group>
        <group name="Sphere_cell080_cell206" position={[0.9588, 0.1099, 0.6174]}>
          <mesh name="Mesh614" geometry={nodes.Mesh614.geometry} material={nodes.Mesh614.material}/>
          <mesh name="Mesh614_1" geometry={nodes.Mesh614_1.geometry} material={nodes.Mesh614_1.material}/>
        </group>
        <group name="Sphere_cell080_cell201" position={[0.976, -0.0648, 0.6033]}>
          <mesh name="Mesh609" geometry={nodes.Mesh609.geometry} material={nodes.Mesh609.material}/>
          <mesh name="Mesh609_1" geometry={nodes.Mesh609_1.geometry} material={nodes.Mesh609_1.material}/>
        </group>
        <group name="Sphere_cell080_cell198" position={[-0.8042, -0.1675, 0.8278]}>
          <mesh name="Mesh606" geometry={nodes.Mesh606.geometry} material={nodes.Mesh606.material}/>
          <mesh name="Mesh606_1" geometry={nodes.Mesh606_1.geometry} material={nodes.Mesh606_1.material}/>
        </group>
        <group name="Sphere_cell080_cell190" position={[-0.7839, 0.0382, 0.866]}>
          <mesh name="Mesh598" geometry={nodes.Mesh598.geometry} material={nodes.Mesh598.material}/>
          <mesh name="Mesh598_1" geometry={nodes.Mesh598_1.geometry} material={nodes.Mesh598_1.material}/>
        </group>
        <group name="Sphere_cell080_cell187" position={[-0.6164, 0.0621, 0.9819]}>
          <mesh name="Mesh595" geometry={nodes.Mesh595.geometry} material={nodes.Mesh595.material}/>
          <mesh name="Mesh595_1" geometry={nodes.Mesh595_1.geometry} material={nodes.Mesh595_1.material}/>
        </group>
        <group name="Sphere_cell080_cell184" position={[-0.3892, 0.0241, 1.0936]}>
          <mesh name="Mesh592" geometry={nodes.Mesh592.geometry} material={nodes.Mesh592.material}/>
          <mesh name="Mesh592_1" geometry={nodes.Mesh592_1.geometry} material={nodes.Mesh592_1.material}/>
        </group>
        <group name="Sphere_cell080_cell182" position={[-0.6372, -0.0513, 0.9783]}>
          <mesh name="Mesh590" geometry={nodes.Mesh590.geometry} material={nodes.Mesh590.material}/>
          <mesh name="Mesh590_1" geometry={nodes.Mesh590_1.geometry} material={nodes.Mesh590_1.material}/>
        </group>
        <group name="Sphere_cell080_cell181" position={[-0.2692, -0.0852, 1.13]}>
          <mesh name="Mesh589" geometry={nodes.Mesh589.geometry} material={nodes.Mesh589.material}/>
          <mesh name="Mesh589_1" geometry={nodes.Mesh589_1.geometry} material={nodes.Mesh589_1.material}/>
        </group>
        <group name="Sphere_cell080_cell180" position={[0.5752, 0.0454, 1.0129]}>
          <mesh name="Mesh588" geometry={nodes.Mesh588.geometry} material={nodes.Mesh588.material}/>
          <mesh name="Mesh588_1" geometry={nodes.Mesh588_1.geometry} material={nodes.Mesh588_1.material}/>
        </group>
        <group name="Sphere_cell080_cell174" position={[0.7268, 0.1821, 0.8771]}>
          <mesh name="Mesh582" geometry={nodes.Mesh582.geometry} material={nodes.Mesh582.material}/>
          <mesh name="Mesh582_1" geometry={nodes.Mesh582_1.geometry} material={nodes.Mesh582_1.material}/>
        </group>
        <group name="Sphere_cell080_cell172" position={[0.6236, 0.1083, 0.9681]}>
          <mesh name="Mesh580" geometry={nodes.Mesh580.geometry} material={nodes.Mesh580.material}/>
          <mesh name="Mesh580_1" geometry={nodes.Mesh580_1.geometry} material={nodes.Mesh580_1.material}/>
        </group>
        <group name="Sphere_cell080_cell171" position={[0.7107, -0.0027, 0.9112]}>
          <mesh name="Mesh579" geometry={nodes.Mesh579.geometry} material={nodes.Mesh579.material}/>
          <mesh name="Mesh579_1" geometry={nodes.Mesh579_1.geometry} material={nodes.Mesh579_1.material}/>
        </group>
        <group name="Sphere_cell080_cell170" position={[-0.2189, -0.116, -1.1144]}>
          <mesh name="Mesh578" geometry={nodes.Mesh578.geometry} material={nodes.Mesh578.material}/>
          <mesh name="Mesh578_1" geometry={nodes.Mesh578_1.geometry} material={nodes.Mesh578_1.material}/>
        </group>
        <group name="Sphere_cell080_cell168" position={[0.2724, -0.0928, -1.0939]}>
          <mesh name="Mesh576" geometry={nodes.Mesh576.geometry} material={nodes.Mesh576.material}/>
          <mesh name="Mesh576_1" geometry={nodes.Mesh576_1.geometry} material={nodes.Mesh576_1.material}/>
        </group>
        <group name="Sphere_cell080_cell166" position={[0.0956, -0.0933, -1.1249]}>
          <mesh name="Mesh574" geometry={nodes.Mesh574.geometry} material={nodes.Mesh574.material}/>
          <mesh name="Mesh574_1" geometry={nodes.Mesh574_1.geometry} material={nodes.Mesh574_1.material}/>
        </group>
        <group name="Sphere_cell080_cell162" position={[-0.0856, -0.1021, -1.1263]}>
          <mesh name="Mesh570" geometry={nodes.Mesh570.geometry} material={nodes.Mesh570.material}/>
          <mesh name="Mesh570_1" geometry={nodes.Mesh570_1.geometry} material={nodes.Mesh570_1.material}/>
        </group>
        <group name="Sphere_cell080_cell159" position={[-0.0769, 0.0899, 1.1693]}>
          <mesh name="Mesh567" geometry={nodes.Mesh567.geometry} material={nodes.Mesh567.material}/>
          <mesh name="Mesh567_1" geometry={nodes.Mesh567_1.geometry} material={nodes.Mesh567_1.material}/>
        </group>
        <group name="Sphere_cell080_cell157" position={[-0.1478, 0.0961, 1.1519]}>
          <mesh name="Mesh565" geometry={nodes.Mesh565.geometry} material={nodes.Mesh565.material}/>
          <mesh name="Mesh565_1" geometry={nodes.Mesh565_1.geometry} material={nodes.Mesh565_1.material}/>
        </group>
        <group name="Sphere_cell080_cell151" position={[-0.1371, 0.0131, 1.1621]}>
          <mesh name="Mesh559" geometry={nodes.Mesh559.geometry} material={nodes.Mesh559.material}/>
          <mesh name="Mesh559_1" geometry={nodes.Mesh559_1.geometry} material={nodes.Mesh559_1.material}/>
        </group>
        <group name="Sphere_cell080_cell150" position={[0.3913, 0.0847, -1.061]}>
          <mesh name="Mesh558" geometry={nodes.Mesh558.geometry} material={nodes.Mesh558.material}/>
          <mesh name="Mesh558_1" geometry={nodes.Mesh558_1.geometry} material={nodes.Mesh558_1.material}/>
        </group>
        <group name="Sphere_cell080_cell149" position={[0.5158, 0.2079, -0.9795]}>
          <mesh name="Mesh557" geometry={nodes.Mesh557.geometry} material={nodes.Mesh557.material}/>
          <mesh name="Mesh557_1" geometry={nodes.Mesh557_1.geometry} material={nodes.Mesh557_1.material}/>
        </group>
        <group name="Sphere_cell080_cell147" position={[0.602, -0.0076, -0.9601]}>
          <mesh name="Mesh555" geometry={nodes.Mesh555.geometry} material={nodes.Mesh555.material}/>
          <mesh name="Mesh555_1" geometry={nodes.Mesh555_1.geometry} material={nodes.Mesh555_1.material}/>
        </group>
        <group name="Sphere_cell080_cell143" position={[0.2569, 0.0957, -1.1117]}>
          <mesh name="Mesh551" geometry={nodes.Mesh551.geometry} material={nodes.Mesh551.material}/>
          <mesh name="Mesh551_1" geometry={nodes.Mesh551_1.geometry} material={nodes.Mesh551_1.material}/>
        </group>
        <group name="Sphere_cell080_cell140" position={[-0.3425, 0, -1.0895]}>
          <mesh name="Mesh548" geometry={nodes.Mesh548.geometry} material={nodes.Mesh548.material}/>
          <mesh name="Mesh548_1" geometry={nodes.Mesh548_1.geometry} material={nodes.Mesh548_1.material}/>
        </group>
        <group name="Sphere_cell080_cell139" position={[-0.2546, 0.1936, -1.0882]}>
          <mesh name="Mesh547" geometry={nodes.Mesh547.geometry} material={nodes.Mesh547.material}/>
          <mesh name="Mesh547_1" geometry={nodes.Mesh547_1.geometry} material={nodes.Mesh547_1.material}/>
        </group>
        <group name="Sphere_cell080_cell134" position={[-0.3624, 0.1212, -1.08]}>
          <mesh name="Mesh542" geometry={nodes.Mesh542.geometry} material={nodes.Mesh542.material}/>
          <mesh name="Mesh542_1" geometry={nodes.Mesh542_1.geometry} material={nodes.Mesh542_1.material}/>
        </group>
        <group name="Sphere_cell080_cell133" position={[-0.5724, 0.1779, -0.9711]}>
          <mesh name="Mesh541" geometry={nodes.Mesh541.geometry} material={nodes.Mesh541.material}/>
          <mesh name="Mesh541_1" geometry={nodes.Mesh541_1.geometry} material={nodes.Mesh541_1.material}/>
        </group>
        <group name="Sphere_cell080_cell127" position={[-1.1374, -0.0275, 0.1844]}>
          <mesh name="Mesh535" geometry={nodes.Mesh535.geometry} material={nodes.Mesh535.material}/>
          <mesh name="Mesh535_1" geometry={nodes.Mesh535_1.geometry} material={nodes.Mesh535_1.material}/>
        </group>
        <group name="Sphere_cell080_cell125" position={[-0.9074, 0.0525, 0.7216]}>
          <mesh name="Mesh533" geometry={nodes.Mesh533.geometry} material={nodes.Mesh533.material}/>
          <mesh name="Mesh533_1" geometry={nodes.Mesh533_1.geometry} material={nodes.Mesh533_1.material}/>
        </group>
        <group name="Sphere_cell080_cell122" position={[-1.0208, -0.1, 0.5155]}>
          <mesh name="Mesh530" geometry={nodes.Mesh530.geometry} material={nodes.Mesh530.material}/>
          <mesh name="Mesh530_1" geometry={nodes.Mesh530_1.geometry} material={nodes.Mesh530_1.material}/>
        </group>
        <group name="Sphere_cell080_cell119" position={[-1.1493, -0.1199, 0.0383]}>
          <mesh name="Mesh527" geometry={nodes.Mesh527.geometry} material={nodes.Mesh527.material}/>
          <mesh name="Mesh527_1" geometry={nodes.Mesh527_1.geometry} material={nodes.Mesh527_1.material}/>
        </group>
        <group name="Sphere_cell080_cell118" position={[-1.1629, 0.0121, -0.0279]}>
          <mesh name="Mesh526" geometry={nodes.Mesh526.geometry} material={nodes.Mesh526.material}/>
          <mesh name="Mesh526_1" geometry={nodes.Mesh526_1.geometry} material={nodes.Mesh526_1.material}/>
        </group>
        <group name="Sphere_cell080_cell106" position={[-0.157, 0.1713, -1.1113]}>
          <mesh name="Mesh514" geometry={nodes.Mesh514.geometry} material={nodes.Mesh514.material}/>
          <mesh name="Mesh514_1" geometry={nodes.Mesh514_1.geometry} material={nodes.Mesh514_1.material}/>
        </group>
        <group name="Sphere_cell080_cell104" position={[-0.0392, 0.197, -1.1142]}>
          <mesh name="Mesh512" geometry={nodes.Mesh512.geometry} material={nodes.Mesh512.material}/>
          <mesh name="Mesh512_1" geometry={nodes.Mesh512_1.geometry} material={nodes.Mesh512_1.material}/>
        </group>
        <group name="Sphere_cell080_cell098" position={[-0.4048, -0.1552, -1.0531]}>
          <mesh name="Mesh506" geometry={nodes.Mesh506.geometry} material={nodes.Mesh506.material}/>
          <mesh name="Mesh506_1" geometry={nodes.Mesh506_1.geometry} material={nodes.Mesh506_1.material}/>
        </group>
        <group name="Sphere_cell080_cell093" position={[-0.5932, -0.1476, -0.9573]}>
          <mesh name="Mesh501" geometry={nodes.Mesh501.geometry} material={nodes.Mesh501.material}/>
          <mesh name="Mesh501_1" geometry={nodes.Mesh501_1.geometry} material={nodes.Mesh501_1.material}/>
        </group>
        <group name="Sphere_cell080_cell091" position={[-0.5142, -0.1585, -1.0118]}>
          <mesh name="Mesh499" geometry={nodes.Mesh499.geometry} material={nodes.Mesh499.material}/>
          <mesh name="Mesh499_1" geometry={nodes.Mesh499_1.geometry} material={nodes.Mesh499_1.material}/>
        </group>
        <group name="Sphere_cell080_cell089" position={[0.3717, -0.0924, 1.0956]}>
          <mesh name="Mesh497" geometry={nodes.Mesh497.geometry} material={nodes.Mesh497.material}/>
          <mesh name="Mesh497_1" geometry={nodes.Mesh497_1.geometry} material={nodes.Mesh497_1.material}/>
        </group>
        <group name="Sphere_cell080_cell085" position={[0.4729, -0.0247, 1.0621]}>
          <mesh name="Mesh493" geometry={nodes.Mesh493.geometry} material={nodes.Mesh493.material}/>
          <mesh name="Mesh493_1" geometry={nodes.Mesh493_1.geometry} material={nodes.Mesh493_1.material}/>
        </group>
        <group name="Sphere_cell080_cell083" position={[0.3289, 0.0523, 1.112]}>
          <mesh name="Mesh491" geometry={nodes.Mesh491.geometry} material={nodes.Mesh491.material}/>
          <mesh name="Mesh491_1" geometry={nodes.Mesh491_1.geometry} material={nodes.Mesh491_1.material}/>
        </group>
        <group name="Sphere_cell080_cell081" position={[0.4431, 0.1415, 1.0564]}>
          <mesh name="Mesh489" geometry={nodes.Mesh489.geometry} material={nodes.Mesh489.material}/>
          <mesh name="Mesh489_1" geometry={nodes.Mesh489_1.geometry} material={nodes.Mesh489_1.material}/>
        </group>
        <group name="Sphere_cell080_cell079" position={[0.2187, 0.0646, 1.1365]}>
          <mesh name="Mesh487" geometry={nodes.Mesh487.geometry} material={nodes.Mesh487.material}/>
          <mesh name="Mesh487_1" geometry={nodes.Mesh487_1.geometry} material={nodes.Mesh487_1.material}/>
        </group>
        <group name="Sphere_cell080_cell078" position={[0.145, -0.0856, 1.1524]}>
          <mesh name="Mesh486" geometry={nodes.Mesh486.geometry} material={nodes.Mesh486.material}/>
          <mesh name="Mesh486_1" geometry={nodes.Mesh486_1.geometry} material={nodes.Mesh486_1.material}/>
        </group>
        <group name="Sphere_cell080_cell076" position={[0.0364, 0.0505, 1.157]}>
          <mesh name="Mesh484" geometry={nodes.Mesh484.geometry} material={nodes.Mesh484.material}/>
          <mesh name="Mesh484_1" geometry={nodes.Mesh484_1.geometry} material={nodes.Mesh484_1.material}/>
        </group>
        <group name="Sphere_cell080_cell068" position={[1.0151, 0.0544, -0.4943]}>
          <mesh name="Mesh476" geometry={nodes.Mesh476.geometry} material={nodes.Mesh476.material}/>
          <mesh name="Mesh476_1" geometry={nodes.Mesh476_1.geometry} material={nodes.Mesh476_1.material}/>
        </group>
        <group name="Sphere_cell080_cell067" position={[1.0467, 0.1247, -0.4311]}>
          <mesh name="Mesh475" geometry={nodes.Mesh475.geometry} material={nodes.Mesh475.material}/>
          <mesh name="Mesh475_1" geometry={nodes.Mesh475_1.geometry} material={nodes.Mesh475_1.material}/>
        </group>
        <group name="Sphere_cell080_cell059" position={[-0.8851, -0.0175, -0.7348]}>
          <mesh name="Mesh467" geometry={nodes.Mesh467.geometry} material={nodes.Mesh467.material}/>
          <mesh name="Mesh467_1" geometry={nodes.Mesh467_1.geometry} material={nodes.Mesh467_1.material}/>
        </group>
        <group name="Sphere_cell080_cell055" position={[-0.9662, 0.0814, -0.6204]}>
          <mesh name="Mesh463" geometry={nodes.Mesh463.geometry} material={nodes.Mesh463.material}/>
          <mesh name="Mesh463_1" geometry={nodes.Mesh463_1.geometry} material={nodes.Mesh463_1.material}/>
        </group>
        <group name="Sphere_cell080_cell054" position={[-0.7463, 0.1401, -0.8588]}>
          <mesh name="Mesh462" geometry={nodes.Mesh462.geometry} material={nodes.Mesh462.material}/>
          <mesh name="Mesh462_1" geometry={nodes.Mesh462_1.geometry} material={nodes.Mesh462_1.material}/>
        </group>
        <group name="Sphere_cell080_cell050" position={[-0.6855, -0.1192, -0.9212]}>
          <mesh name="Mesh458" geometry={nodes.Mesh458.geometry} material={nodes.Mesh458.material}/>
          <mesh name="Mesh458_1" geometry={nodes.Mesh458_1.geometry} material={nodes.Mesh458_1.material}/>
        </group>
        <group name="Sphere_cell080_cell049" position={[-0.5998, -0.0018, -0.975]}>
          <mesh name="Mesh457" geometry={nodes.Mesh457.geometry} material={nodes.Mesh457.material}/>
          <mesh name="Mesh457_1" geometry={nodes.Mesh457_1.geometry} material={nodes.Mesh457_1.material}/>
        </group>
        <group name="Sphere_cell080_cell047" position={[-0.828, -0.08, -0.7937]}>
          <mesh name="Mesh455" geometry={nodes.Mesh455.geometry} material={nodes.Mesh455.material}/>
          <mesh name="Mesh455_1" geometry={nodes.Mesh455_1.geometry} material={nodes.Mesh455_1.material}/>
        </group>
        <group name="Sphere_cell080_cell046" position={[-0.7167, -0.0171, -0.885]}>
          <mesh name="Mesh454" geometry={nodes.Mesh454.geometry} material={nodes.Mesh454.material}/>
          <mesh name="Mesh454_1" geometry={nodes.Mesh454_1.geometry} material={nodes.Mesh454_1.material}/>
        </group>
        <group name="Sphere_cell080_cell045" position={[-0.5766, 0.0535, -0.9834]}>
          <mesh name="Mesh453" geometry={nodes.Mesh453.geometry} material={nodes.Mesh453.material}/>
          <mesh name="Mesh453_1" geometry={nodes.Mesh453_1.geometry} material={nodes.Mesh453_1.material}/>
        </group>
        <group name="Sphere_cell080_cell044" position={[-0.7411, 0.0647, -0.8838]}>
          <mesh name="Mesh452" geometry={nodes.Mesh452.geometry} material={nodes.Mesh452.material}/>
          <mesh name="Mesh452_1" geometry={nodes.Mesh452_1.geometry} material={nodes.Mesh452_1.material}/>
        </group>
        <group name="Sphere_cell080_cell043" position={[-0.6257, 0.0477, -0.9747]}>
          <mesh name="Mesh451" geometry={nodes.Mesh451.geometry} material={nodes.Mesh451.material}/>
          <mesh name="Mesh451_1" geometry={nodes.Mesh451_1.geometry} material={nodes.Mesh451_1.material}/>
        </group>
        <group name="Sphere_cell080_cell042" position={[-0.6748, 0.0893, -0.9253]}>
          <mesh name="Mesh450" geometry={nodes.Mesh450.geometry} material={nodes.Mesh450.material}/>
          <mesh name="Mesh450_1" geometry={nodes.Mesh450_1.geometry} material={nodes.Mesh450_1.material}/>
        </group>
        <group name="Sphere_cell080_cell040" position={[1.0283, -0.0867, 0.5023]}>
          <mesh name="Mesh448" geometry={nodes.Mesh448.geometry} material={nodes.Mesh448.material}/>
          <mesh name="Mesh448_1" geometry={nodes.Mesh448_1.geometry} material={nodes.Mesh448_1.material}/>
        </group>
        <group name="Sphere_cell080_cell039" position={[1.0852, -0.1422, 0.3415]}>
          <mesh name="Mesh447" geometry={nodes.Mesh447.geometry} material={nodes.Mesh447.material}/>
          <mesh name="Mesh447_1" geometry={nodes.Mesh447_1.geometry} material={nodes.Mesh447_1.material}/>
        </group>
        <group name="Sphere_cell080_cell038" position={[1.1142, -0.1198, 0.2373]}>
          <mesh name="Mesh446" geometry={nodes.Mesh446.geometry} material={nodes.Mesh446.material}/>
          <mesh name="Mesh446_1" geometry={nodes.Mesh446_1.geometry} material={nodes.Mesh446_1.material}/>
        </group>
        <group name="Sphere_cell080_cell035" position={[1.0609, 0.1408, 0.4206]}>
          <mesh name="Mesh443" geometry={nodes.Mesh443.geometry} material={nodes.Mesh443.material}/>
          <mesh name="Mesh443_1" geometry={nodes.Mesh443_1.geometry} material={nodes.Mesh443_1.material}/>
        </group>
        <group name="Sphere_cell080_cell034" position={[1.1168, 0.0932, 0.2259]}>
          <mesh name="Mesh442" geometry={nodes.Mesh442.geometry} material={nodes.Mesh442.material}/>
          <mesh name="Mesh442_1" geometry={nodes.Mesh442_1.geometry} material={nodes.Mesh442_1.material}/>
        </group>
        <group name="Sphere_cell080_cell031" position={[1.0558, 0.0416, 0.4608]}>
          <mesh name="Mesh439" geometry={nodes.Mesh439.geometry} material={nodes.Mesh439.material}/>
          <mesh name="Mesh439_1" geometry={nodes.Mesh439_1.geometry} material={nodes.Mesh439_1.material}/>
        </group>
        <group name="Sphere_cell080_cell029" position={[-1.0453, -0.0444, -0.4754]}>
          <mesh name="Mesh437" geometry={nodes.Mesh437.geometry} material={nodes.Mesh437.material}/>
          <mesh name="Mesh437_1" geometry={nodes.Mesh437_1.geometry} material={nodes.Mesh437_1.material}/>
        </group>
        <group name="Sphere_cell080_cell028" position={[-1.1436, 0.1008, -0.1285]}>
          <mesh name="Mesh436" geometry={nodes.Mesh436.geometry} material={nodes.Mesh436.material}/>
          <mesh name="Mesh436_1" geometry={nodes.Mesh436_1.geometry} material={nodes.Mesh436_1.material}/>
        </group>
        <group name="Sphere_cell080_cell027" position={[-1.0972, 0.0742, -0.35]}>
          <mesh name="Mesh435" geometry={nodes.Mesh435.geometry} material={nodes.Mesh435.material}/>
          <mesh name="Mesh435_1" geometry={nodes.Mesh435_1.geometry} material={nodes.Mesh435_1.material}/>
        </group>
        <group name="Sphere_cell080_cell024" position={[-1.1275, -0.0895, -0.2525]}>
          <mesh name="Mesh432" geometry={nodes.Mesh432.geometry} material={nodes.Mesh432.material}/>
          <mesh name="Mesh432_1" geometry={nodes.Mesh432_1.geometry} material={nodes.Mesh432_1.material}/>
        </group>
        <group name="Sphere_cell080_cell019" position={[1.116, 0.078, -0.2287]}>
          <mesh name="Mesh427" geometry={nodes.Mesh427.geometry} material={nodes.Mesh427.material}/>
          <mesh name="Mesh427_1" geometry={nodes.Mesh427_1.geometry} material={nodes.Mesh427_1.material}/>
        </group>
        <group name="Sphere_cell080_cell018" position={[1.0976, -0.2511, 0.1316]}>
          <mesh name="Mesh426" geometry={nodes.Mesh426.geometry} material={nodes.Mesh426.material}/>
          <mesh name="Mesh426_1" geometry={nodes.Mesh426_1.geometry} material={nodes.Mesh426_1.material}/>
        </group>
        <group name="Sphere_cell080_cell015" position={[1.1435, 0.0447, 0.0183]}>
          <mesh name="Mesh423" geometry={nodes.Mesh423.geometry} material={nodes.Mesh423.material}/>
          <mesh name="Mesh423_1" geometry={nodes.Mesh423_1.geometry} material={nodes.Mesh423_1.material}/>
        </group>
        <group name="Sphere_cell080_cell014" position={[1.0899, -0.0494, -0.3297]}>
          <mesh name="Mesh422" geometry={nodes.Mesh422.geometry} material={nodes.Mesh422.material}/>
          <mesh name="Mesh422_1" geometry={nodes.Mesh422_1.geometry} material={nodes.Mesh422_1.material}/>
        </group>
        <group name="Sphere_cell080_cell013" position={[1.1274, 0.016, -0.1152]}>
          <mesh name="Mesh421" geometry={nodes.Mesh421.geometry} material={nodes.Mesh421.material}/>
          <mesh name="Mesh421_1" geometry={nodes.Mesh421_1.geometry} material={nodes.Mesh421_1.material}/>
        </group>
        <group name="Sphere_cell080_cell010" position={[0.7444, 0.0381, -0.866]}>
          <mesh name="Mesh418" geometry={nodes.Mesh418.geometry} material={nodes.Mesh418.material}/>
          <mesh name="Mesh418_1" geometry={nodes.Mesh418_1.geometry} material={nodes.Mesh418_1.material}/>
        </group>
        <group name="Sphere_cell080_cell004" position={[0.8901, 0.0658, -0.6848]}>
          <mesh name="Mesh413" geometry={nodes.Mesh413.geometry} material={nodes.Mesh413.material}/>
          <mesh name="Mesh413_1" geometry={nodes.Mesh413_1.geometry} material={nodes.Mesh413_1.material}/>
        </group>
        <group name="Sphere_cell080_cell003" position={[0.8662, -0.0947, -0.7308]}>
          <mesh name="Mesh412" geometry={nodes.Mesh412.geometry} material={nodes.Mesh412.material}/>
          <mesh name="Mesh412_1" geometry={nodes.Mesh412_1.geometry} material={nodes.Mesh412_1.material}/>
        </group>
        <group name="Sphere_cell080_cell002" position={[0.7263, -0.0894, -0.8611]}>
          <mesh name="Mesh411" geometry={nodes.Mesh411.geometry} material={nodes.Mesh411.material}/>
          <mesh name="Mesh411_1" geometry={nodes.Mesh411_1.geometry} material={nodes.Mesh411_1.material}/>
        </group>
        <group name="Sphere_cell080_cell006" position={[0.861, 0.3533, 0.6737]}>
          <mesh name="Mesh225" geometry={nodes.Mesh225.geometry} material={nodes.Mesh225.material}/>
          <mesh name="Mesh225_1" geometry={nodes.Mesh225_1.geometry} material={nodes.Mesh225_1.material}/>
        </group>
        <group name="Sphere_cell080_cell207" position={[0.9232, 0.2426, 0.4556]}>
          <mesh name="Mesh615" geometry={nodes.Mesh615.geometry} material={nodes.Mesh615.material}/>
          <mesh name="Mesh615_1" geometry={nodes.Mesh615_1.geometry} material={nodes.Mesh615_1.material}/>
        </group>
        <group name="Sphere_cell080_cell205" position={[0.8848, 0.369, 0.4486]}>
          <mesh name="Mesh613" geometry={nodes.Mesh613.geometry} material={nodes.Mesh613.material}/>
          <mesh name="Mesh613_1" geometry={nodes.Mesh613_1.geometry} material={nodes.Mesh613_1.material}/>
        </group>
        <group name="Sphere_cell080_cell204" position={[0.8593, 0.4508, 0.4371]}>
          <mesh name="Mesh612" geometry={nodes.Mesh612.geometry} material={nodes.Mesh612.material}/>
          <mesh name="Mesh612_1" geometry={nodes.Mesh612_1.geometry} material={nodes.Mesh612_1.material}/>
        </group>
        <group name="Sphere_cell080_cell203" position={[0.7703, 0.486, 0.5389]}>
          <mesh name="Mesh611" geometry={nodes.Mesh611.geometry} material={nodes.Mesh611.material}/>
          <mesh name="Mesh611_1" geometry={nodes.Mesh611_1.geometry} material={nodes.Mesh611_1.material}/>
        </group>
        <group name="Sphere_cell080_cell202" position={[0.7352, 0.3059, 0.6997]}>
          <mesh name="Mesh610" geometry={nodes.Mesh610.geometry} material={nodes.Mesh610.material}/>
          <mesh name="Mesh610_1" geometry={nodes.Mesh610_1.geometry} material={nodes.Mesh610_1.material}/>
        </group>
        <group name="Sphere_cell080_cell200" position={[-0.6045, -0.338, 0.7923]}>
          <mesh name="Mesh608" geometry={nodes.Mesh608.geometry} material={nodes.Mesh608.material}/>
          <mesh name="Mesh608_1" geometry={nodes.Mesh608_1.geometry} material={nodes.Mesh608_1.material}/>
        </group>
        <group name="Sphere_cell080_cell199" position={[-0.6429, -0.1256, 0.8259]}>
          <mesh name="Mesh607" geometry={nodes.Mesh607.geometry} material={nodes.Mesh607.material}/>
          <mesh name="Mesh607_1" geometry={nodes.Mesh607_1.geometry} material={nodes.Mesh607_1.material}/>
        </group>
        <group name="Sphere_cell080_cell197" position={[-0.6266, -0.4429, 0.7239]}>
          <mesh name="Mesh605" geometry={nodes.Mesh605.geometry} material={nodes.Mesh605.material}/>
          <mesh name="Mesh605_1" geometry={nodes.Mesh605_1.geometry} material={nodes.Mesh605_1.material}/>
        </group>
        <group name="Sphere_cell080_cell196" position={[-0.4278, -0.3915, 0.8816]}>
          <mesh name="Mesh604" geometry={nodes.Mesh604.geometry} material={nodes.Mesh604.material}/>
          <mesh name="Mesh604_1" geometry={nodes.Mesh604_1.geometry} material={nodes.Mesh604_1.material}/>
        </group>
        <group name="Sphere_cell080_cell195" position={[-0.4259, -0.2338, 0.9365]}>
          <mesh name="Mesh603" geometry={nodes.Mesh603.geometry} material={nodes.Mesh603.material}/>
          <mesh name="Mesh603_1" geometry={nodes.Mesh603_1.geometry} material={nodes.Mesh603_1.material}/>
        </group>
        <group name="Sphere_cell080_cell194" position={[-0.4608, -0.556, 0.7701]}>
          <mesh name="Mesh602" geometry={nodes.Mesh602.geometry} material={nodes.Mesh602.material}/>
          <mesh name="Mesh602_1" geometry={nodes.Mesh602_1.geometry} material={nodes.Mesh602_1.material}/>
        </group>
        <group name="Sphere_cell080_cell193" position={[-0.5136, -0.1922, 0.9039]}>
          <mesh name="Mesh601" geometry={nodes.Mesh601.geometry} material={nodes.Mesh601.material}/>
          <mesh name="Mesh601_1" geometry={nodes.Mesh601_1.geometry} material={nodes.Mesh601_1.material}/>
        </group>
        <group name="Sphere_cell080_cell192" position={[-0.5535, -0.5356, 0.7349]}>
          <mesh name="Mesh600" geometry={nodes.Mesh600.geometry} material={nodes.Mesh600.material}/>
          <mesh name="Mesh600_1" geometry={nodes.Mesh600_1.geometry} material={nodes.Mesh600_1.material}/>
        </group>
        <group name="Sphere_cell080_cell191" position={[-0.5883, -0.1526, 0.8679]}>
          <mesh name="Mesh599" geometry={nodes.Mesh599.geometry} material={nodes.Mesh599.material}/>
          <mesh name="Mesh599_1" geometry={nodes.Mesh599_1.geometry} material={nodes.Mesh599_1.material}/>
        </group>
        <group name="Sphere_cell080_cell189" position={[-0.4241, 0.2944, 0.9264]}>
          <mesh name="Mesh597" geometry={nodes.Mesh597.geometry} material={nodes.Mesh597.material}/>
          <mesh name="Mesh597_1" geometry={nodes.Mesh597_1.geometry} material={nodes.Mesh597_1.material}/>
        </group>
        <group name="Sphere_cell080_cell188" position={[-0.3302, 0.2554, 0.9717]}>
          <mesh name="Mesh596" geometry={nodes.Mesh596.geometry} material={nodes.Mesh596.material}/>
          <mesh name="Mesh596_1" geometry={nodes.Mesh596_1.geometry} material={nodes.Mesh596_1.material}/>
        </group>
        <group name="Sphere_cell080_cell186" position={[-0.7217, 0.2289, 0.7404]}>
          <mesh name="Mesh594" geometry={nodes.Mesh594.geometry} material={nodes.Mesh594.material}/>
          <mesh name="Mesh594_1" geometry={nodes.Mesh594_1.geometry} material={nodes.Mesh594_1.material}/>
        </group>
        <group name="Sphere_cell080_cell185" position={[-0.6683, 0.1783, 0.7945]}>
          <mesh name="Mesh593" geometry={nodes.Mesh593.geometry} material={nodes.Mesh593.material}/>
          <mesh name="Mesh593_1" geometry={nodes.Mesh593_1.geometry} material={nodes.Mesh593_1.material}/>
        </group>
        <group name="Sphere_cell080_cell183" position={[-0.456, 0.2065, 0.9278]}>
          <mesh name="Mesh591" geometry={nodes.Mesh591.geometry} material={nodes.Mesh591.material}/>
          <mesh name="Mesh591_1" geometry={nodes.Mesh591_1.geometry} material={nodes.Mesh591_1.material}/>
        </group>
        <group name="Sphere_cell080_cell179" position={[0.5824, 0.2863, 0.8396]}>
          <mesh name="Mesh587" geometry={nodes.Mesh587.geometry} material={nodes.Mesh587.material}/>
          <mesh name="Mesh587_1" geometry={nodes.Mesh587_1.geometry} material={nodes.Mesh587_1.material}/>
        </group>
        <group name="Sphere_cell080_cell178" position={[0.5541, 0.1915, 0.8807]}>
          <mesh name="Mesh586" geometry={nodes.Mesh586.geometry} material={nodes.Mesh586.material}/>
          <mesh name="Mesh586_1" geometry={nodes.Mesh586_1.geometry} material={nodes.Mesh586_1.material}/>
        </group>
        <group name="Sphere_cell080_cell177" position={[0.5709, -0.1048, 0.8873]}>
          <mesh name="Mesh585" geometry={nodes.Mesh585.geometry} material={nodes.Mesh585.material}/>
          <mesh name="Mesh585_1" geometry={nodes.Mesh585_1.geometry} material={nodes.Mesh585_1.material}/>
        </group>
        <group name="Sphere_cell080_cell176" position={[0.6014, -0.1739, 0.8633]}>
          <mesh name="Mesh584" geometry={nodes.Mesh584.geometry} material={nodes.Mesh584.material}/>
          <mesh name="Mesh584_1" geometry={nodes.Mesh584_1.geometry} material={nodes.Mesh584_1.material}/>
        </group>
        <group name="Sphere_cell080_cell175" position={[0.5334, -0.2363, 0.888]}>
          <mesh name="Mesh583" geometry={nodes.Mesh583.geometry} material={nodes.Mesh583.material}/>
          <mesh name="Mesh583_1" geometry={nodes.Mesh583_1.geometry} material={nodes.Mesh583_1.material}/>
        </group>
        <group name="Sphere_cell080_cell173" position={[0.6602, 0.3237, 0.7664]}>
          <mesh name="Mesh581" geometry={nodes.Mesh581.geometry} material={nodes.Mesh581.material}/>
          <mesh name="Mesh581_1" geometry={nodes.Mesh581_1.geometry} material={nodes.Mesh581_1.material}/>
        </group>
        <group name="Sphere_cell080_cell169" position={[0.1665, -0.3642, -0.972]}>
          <mesh name="Mesh577" geometry={nodes.Mesh577.geometry} material={nodes.Mesh577.material}/>
          <mesh name="Mesh577_1" geometry={nodes.Mesh577_1.geometry} material={nodes.Mesh577_1.material}/>
        </group>
        <group name="Sphere_cell080_cell167" position={[-0.0336, -0.2686, -1.0139]}>
          <mesh name="Mesh575" geometry={nodes.Mesh575.geometry} material={nodes.Mesh575.material}/>
          <mesh name="Mesh575_1" geometry={nodes.Mesh575_1.geometry} material={nodes.Mesh575_1.material}/>
        </group>
        <group name="Sphere_cell080_cell165" position={[0.3444, -0.3661, -0.9413]}>
          <mesh name="Mesh573" geometry={nodes.Mesh573.geometry} material={nodes.Mesh573.material}/>
          <mesh name="Mesh573_1" geometry={nodes.Mesh573_1.geometry} material={nodes.Mesh573_1.material}/>
        </group>
        <group name="Sphere_cell080_cell164" position={[0.4344, -0.2042, -0.9362]}>
          <mesh name="Mesh572" geometry={nodes.Mesh572.geometry} material={nodes.Mesh572.material}/>
          <mesh name="Mesh572_1" geometry={nodes.Mesh572_1.geometry} material={nodes.Mesh572_1.material}/>
        </group>
        <group name="Sphere_cell080_cell163" position={[0.3062, -0.4531, -0.897]}>
          <mesh name="Mesh571" geometry={nodes.Mesh571.geometry} material={nodes.Mesh571.material}/>
          <mesh name="Mesh571_1" geometry={nodes.Mesh571_1.geometry} material={nodes.Mesh571_1.material}/>
        </group>
        <group name="Sphere_cell080_cell161" position={[0.4215, -0.3302, -0.8984]}>
          <mesh name="Mesh569" geometry={nodes.Mesh569.geometry} material={nodes.Mesh569.material}/>
          <mesh name="Mesh569_1" geometry={nodes.Mesh569_1.geometry} material={nodes.Mesh569_1.material}/>
        </group>
        <group name="Sphere_cell080_cell160" position={[-0.061, 0.2154, 1.0356]}>
          <mesh name="Mesh568" geometry={nodes.Mesh568.geometry} material={nodes.Mesh568.material}/>
          <mesh name="Mesh568_1" geometry={nodes.Mesh568_1.geometry} material={nodes.Mesh568_1.material}/>
        </group>
        <group name="Sphere_cell080_cell158" position={[-0.2623, 0.314, 0.9771]}>
          <mesh name="Mesh566" geometry={nodes.Mesh566.geometry} material={nodes.Mesh566.material}/>
          <mesh name="Mesh566_1" geometry={nodes.Mesh566_1.geometry} material={nodes.Mesh566_1.material}/>
        </group>
        <group name="Sphere_cell080_cell156" position={[0.0945, 0.2777, 1.0192]}>
          <mesh name="Mesh564" geometry={nodes.Mesh564.geometry} material={nodes.Mesh564.material}/>
          <mesh name="Mesh564_1" geometry={nodes.Mesh564_1.geometry} material={nodes.Mesh564_1.material}/>
        </group>
        <group name="Sphere_cell080_cell155" position={[-0.1714, 0.3122, 0.9909]}>
          <mesh name="Mesh563" geometry={nodes.Mesh563.geometry} material={nodes.Mesh563.material}/>
          <mesh name="Mesh563_1" geometry={nodes.Mesh563_1.geometry} material={nodes.Mesh563_1.material}/>
        </group>
        <group name="Sphere_cell080_cell154" position={[-0.1923, 0.1664, 1.0255]}>
          <mesh name="Mesh562" geometry={nodes.Mesh562.geometry} material={nodes.Mesh562.material}/>
          <mesh name="Mesh562_1" geometry={nodes.Mesh562_1.geometry} material={nodes.Mesh562_1.material}/>
        </group>
        <group name="Sphere_cell080_cell153" position={[0.0589, 0.171, 1.041]}>
          <mesh name="Mesh561" geometry={nodes.Mesh561.geometry} material={nodes.Mesh561.material}/>
          <mesh name="Mesh561_1" geometry={nodes.Mesh561_1.geometry} material={nodes.Mesh561_1.material}/>
        </group>
        <group name="Sphere_cell080_cell152" position={[-0.0461, 0.3939, 0.9789]}>
          <mesh name="Mesh560" geometry={nodes.Mesh560.geometry} material={nodes.Mesh560.material}/>
          <mesh name="Mesh560_1" geometry={nodes.Mesh560_1.geometry} material={nodes.Mesh560_1.material}/>
        </group>
        <group name="Sphere_cell080_cell148" position={[0.5473, -0.1564, -0.8817]}>
          <mesh name="Mesh556" geometry={nodes.Mesh556.geometry} material={nodes.Mesh556.material}/>
          <mesh name="Mesh556_1" geometry={nodes.Mesh556_1.geometry} material={nodes.Mesh556_1.material}/>
        </group>
        <group name="Sphere_cell080_cell146" position={[0.6251, 0.26, -0.8069]}>
          <mesh name="Mesh554" geometry={nodes.Mesh554.geometry} material={nodes.Mesh554.material}/>
          <mesh name="Mesh554_1" geometry={nodes.Mesh554_1.geometry} material={nodes.Mesh554_1.material}/>
        </group>
        <group name="Sphere_cell080_cell145" position={[0.4944, -0.1011, -0.9303]}>
          <mesh name="Mesh553" geometry={nodes.Mesh553.geometry} material={nodes.Mesh553.material}/>
          <mesh name="Mesh553_1" geometry={nodes.Mesh553_1.geometry} material={nodes.Mesh553_1.material}/>
        </group>
        <group name="Sphere_cell080_cell144" position={[0.234, 0.1608, -1.0131]}>
          <mesh name="Mesh552" geometry={nodes.Mesh552.geometry} material={nodes.Mesh552.material}/>
          <mesh name="Mesh552_1" geometry={nodes.Mesh552_1.geometry} material={nodes.Mesh552_1.material}/>
        </group>
        <group name="Sphere_cell080_cell142" position={[0.3215, 0.3012, -0.9595]}>
          <mesh name="Mesh550" geometry={nodes.Mesh550.geometry} material={nodes.Mesh550.material}/>
          <mesh name="Mesh550_1" geometry={nodes.Mesh550_1.geometry} material={nodes.Mesh550_1.material}/>
        </group>
        <group name="Sphere_cell080_cell141" position={[0.4738, 0.3882, -0.861]}>
          <mesh name="Mesh549" geometry={nodes.Mesh549.geometry} material={nodes.Mesh549.material}/>
          <mesh name="Mesh549_1" geometry={nodes.Mesh549_1.geometry} material={nodes.Mesh549_1.material}/>
        </group>
        <group name="Sphere_cell080_cell138" position={[-0.2245, 0.362, -0.9594]}>
          <mesh name="Mesh546" geometry={nodes.Mesh546.geometry} material={nodes.Mesh546.material}/>
          <mesh name="Mesh546_1" geometry={nodes.Mesh546_1.geometry} material={nodes.Mesh546_1.material}/>
        </group>
        <group name="Sphere_cell080_cell137" position={[-0.3629, 0.2161, -0.9581]}>
          <mesh name="Mesh545" geometry={nodes.Mesh545.geometry} material={nodes.Mesh545.material}/>
          <mesh name="Mesh545_1" geometry={nodes.Mesh545_1.geometry} material={nodes.Mesh545_1.material}/>
        </group>
        <group name="Sphere_cell080_cell136" position={[-0.531, 0.3963, -0.8155]}>
          <mesh name="Mesh544" geometry={nodes.Mesh544.geometry} material={nodes.Mesh544.material}/>
          <mesh name="Mesh544_1" geometry={nodes.Mesh544_1.geometry} material={nodes.Mesh544_1.material}/>
        </group>
        <group name="Sphere_cell080_cell135" position={[-0.4086, 0.3459, -0.9071]}>
          <mesh name="Mesh543" geometry={nodes.Mesh543.geometry} material={nodes.Mesh543.material}/>
          <mesh name="Mesh543_1" geometry={nodes.Mesh543_1.geometry} material={nodes.Mesh543_1.material}/>
        </group>
        <group name="Sphere_cell080_cell132" position={[-0.1746, 0.5224, -0.9028]}>
          <mesh name="Mesh540" geometry={nodes.Mesh540.geometry} material={nodes.Mesh540.material}/>
          <mesh name="Mesh540_1" geometry={nodes.Mesh540_1.geometry} material={nodes.Mesh540_1.material}/>
        </group>
        <group name="Sphere_cell080_cell131" position={[-0.2811, 0.5488, -0.8482]}>
          <mesh name="Mesh539" geometry={nodes.Mesh539.geometry} material={nodes.Mesh539.material}/>
          <mesh name="Mesh539_1" geometry={nodes.Mesh539_1.geometry} material={nodes.Mesh539_1.material}/>
        </group>
        <group name="Sphere_cell080_cell130" position={[-0.9105, -0.3147, 0.4181]}>
          <mesh name="Mesh538" geometry={nodes.Mesh538.geometry} material={nodes.Mesh538.material}/>
          <mesh name="Mesh538_1" geometry={nodes.Mesh538_1.geometry} material={nodes.Mesh538_1.material}/>
        </group>
        <group name="Sphere_cell080_cell129" position={[-0.9735, -0.3009, 0.2608]}>
          <mesh name="Mesh537" geometry={nodes.Mesh537.geometry} material={nodes.Mesh537.material}/>
          <mesh name="Mesh537_1" geometry={nodes.Mesh537_1.geometry} material={nodes.Mesh537_1.material}/>
        </group>
        <group name="Sphere_cell080_cell128" position={[-0.8056, 0.2699, 0.6051]}>
          <mesh name="Mesh536" geometry={nodes.Mesh536.geometry} material={nodes.Mesh536.material}/>
          <mesh name="Mesh536_1" geometry={nodes.Mesh536_1.geometry} material={nodes.Mesh536_1.material}/>
        </group>
        <group name="Sphere_cell080_cell126" position={[-0.9749, 0.3033, 0.206]}>
          <mesh name="Mesh534" geometry={nodes.Mesh534.geometry} material={nodes.Mesh534.material}/>
          <mesh name="Mesh534_1" geometry={nodes.Mesh534_1.geometry} material={nodes.Mesh534_1.material}/>
        </group>
        <group name="Sphere_cell080_cell124" position={[-0.8075, 0.2251, 0.6484]}>
          <mesh name="Mesh532" geometry={nodes.Mesh532.geometry} material={nodes.Mesh532.material}/>
          <mesh name="Mesh532_1" geometry={nodes.Mesh532_1.geometry} material={nodes.Mesh532_1.material}/>
        </group>
        <group name="Sphere_cell080_cell123" position={[-0.9032, 0.2226, 0.4923]}>
          <mesh name="Mesh531" geometry={nodes.Mesh531.geometry} material={nodes.Mesh531.material}/>
          <mesh name="Mesh531_1" geometry={nodes.Mesh531_1.geometry} material={nodes.Mesh531_1.material}/>
        </group>
        <group name="Sphere_cell080_cell121" position={[-0.8711, 0.3636, 0.4509]}>
          <mesh name="Mesh529" geometry={nodes.Mesh529.geometry} material={nodes.Mesh529.material}/>
          <mesh name="Mesh529_1" geometry={nodes.Mesh529_1.geometry} material={nodes.Mesh529_1.material}/>
        </group>
        <group name="Sphere_cell080_cell120" position={[-1.0434, -0.1189, -0.0806]}>
          <mesh name="Mesh528" geometry={nodes.Mesh528.geometry} material={nodes.Mesh528.material}/>
          <mesh name="Mesh528_1" geometry={nodes.Mesh528_1.geometry} material={nodes.Mesh528_1.material}/>
        </group>
        <group name="Sphere_cell080_cell117" position={[-0.8994, -0.4032, -0.3729]}>
          <mesh name="Mesh525" geometry={nodes.Mesh525.geometry} material={nodes.Mesh525.material}/>
          <mesh name="Mesh525_1" geometry={nodes.Mesh525_1.geometry} material={nodes.Mesh525_1.material}/>
        </group>
        <group name="Sphere_cell080_cell116" position={[-1.0077, -0.2897, -0.0178]}>
          <mesh name="Mesh524" geometry={nodes.Mesh524.geometry} material={nodes.Mesh524.material}/>
          <mesh name="Mesh524_1" geometry={nodes.Mesh524_1.geometry} material={nodes.Mesh524_1.material}/>
        </group>
        <group name="Sphere_cell080_cell115" position={[-0.9615, -0.4337, 0.0178]}>
          <mesh name="Mesh523" geometry={nodes.Mesh523.geometry} material={nodes.Mesh523.material}/>
          <mesh name="Mesh523_1" geometry={nodes.Mesh523_1.geometry} material={nodes.Mesh523_1.material}/>
        </group>
        <group name="Sphere_cell080_cell114" position={[-1.0058, -0.2294, -0.2174]}>
          <mesh name="Mesh522" geometry={nodes.Mesh522.geometry} material={nodes.Mesh522.material}/>
          <mesh name="Mesh522_1" geometry={nodes.Mesh522_1.geometry} material={nodes.Mesh522_1.material}/>
        </group>
        <group name="Sphere_cell080_cell113" position={[-0.9434, -0.3738, -0.2755]}>
          <mesh name="Mesh521" geometry={nodes.Mesh521.geometry} material={nodes.Mesh521.material}/>
          <mesh name="Mesh521_1" geometry={nodes.Mesh521_1.geometry} material={nodes.Mesh521_1.material}/>
        </group>
        <group name="Sphere_cell080_cell112" position={[-0.9524, -0.4294, -0.1354]}>
          <mesh name="Mesh520" geometry={nodes.Mesh520.geometry} material={nodes.Mesh520.material}/>
          <mesh name="Mesh520_1" geometry={nodes.Mesh520_1.geometry} material={nodes.Mesh520_1.material}/>
        </group>
        <group name="Sphere_cell080_cell111" position={[-0.9656, -0.3908, 0.15]}>
          <mesh name="Mesh519" geometry={nodes.Mesh519.geometry} material={nodes.Mesh519.material}/>
          <mesh name="Mesh519_1" geometry={nodes.Mesh519_1.geometry} material={nodes.Mesh519_1.material}/>
        </group>
        <group name="Sphere_cell080_cell110" position={[0.0257, 0.4233, -0.9893]}>
          <mesh name="Mesh518" geometry={nodes.Mesh518.geometry} material={nodes.Mesh518.material}/>
          <mesh name="Mesh518_1" geometry={nodes.Mesh518_1.geometry} material={nodes.Mesh518_1.material}/>
        </group>
        <group name="Sphere_cell080_cell109" position={[0.1991, 0.2923, -0.9972]}>
          <mesh name="Mesh517" geometry={nodes.Mesh517.geometry} material={nodes.Mesh517.material}/>
          <mesh name="Mesh517_1" geometry={nodes.Mesh517_1.geometry} material={nodes.Mesh517_1.material}/>
        </group>
        <group name="Sphere_cell080_cell108" position={[-0.0989, 0.3949, -0.9688]}>
          <mesh name="Mesh516" geometry={nodes.Mesh516.geometry} material={nodes.Mesh516.material}/>
          <mesh name="Mesh516_1" geometry={nodes.Mesh516_1.geometry} material={nodes.Mesh516_1.material}/>
        </group>
        <group name="Sphere_cell080_cell107" position={[0.1966, 0.3771, -0.9624]}>
          <mesh name="Mesh515" geometry={nodes.Mesh515.geometry} material={nodes.Mesh515.material}/>
          <mesh name="Mesh515_1" geometry={nodes.Mesh515_1.geometry} material={nodes.Mesh515_1.material}/>
        </group>
        <group name="Sphere_cell080_cell105" position={[0.1118, 0.2335, -1.0114]}>
          <mesh name="Mesh513" geometry={nodes.Mesh513.geometry} material={nodes.Mesh513.material}/>
          <mesh name="Mesh513_1" geometry={nodes.Mesh513_1.geometry} material={nodes.Mesh513_1.material}/>
        </group>
        <group name="Sphere_cell080_cell103" position={[0.0336, 0.4206, -0.9439]}>
          <mesh name="Mesh511" geometry={nodes.Mesh511.geometry} material={nodes.Mesh511.material}/>
          <mesh name="Mesh511_1" geometry={nodes.Mesh511_1.geometry} material={nodes.Mesh511_1.material}/>
        </group>
        <group name="Sphere_cell080_cell102" position={[0.1533, 0.267, -1.0122]}>
          <mesh name="Mesh510" geometry={nodes.Mesh510.geometry} material={nodes.Mesh510.material}/>
          <mesh name="Mesh510_1" geometry={nodes.Mesh510_1.geometry} material={nodes.Mesh510_1.material}/>
        </group>
        <group name="Sphere_cell080_cell101" position={[-0.0509, 0.5071, -0.9247]}>
          <mesh name="Mesh509" geometry={nodes.Mesh509.geometry} material={nodes.Mesh509.material}/>
          <mesh name="Mesh509_1" geometry={nodes.Mesh509_1.geometry} material={nodes.Mesh509_1.material}/>
        </group>
        <group name="Sphere_cell080_cell100" position={[-0.5943, -0.273, -0.8332]}>
          <mesh name="Mesh508" geometry={nodes.Mesh508.geometry} material={nodes.Mesh508.material}/>
          <mesh name="Mesh508_1" geometry={nodes.Mesh508_1.geometry} material={nodes.Mesh508_1.material}/>
        </group>
        <group name="Sphere_cell080_cell099" position={[-0.5526, -0.3596, -0.8197]}>
          <mesh name="Mesh507" geometry={nodes.Mesh507.geometry} material={nodes.Mesh507.material}/>
          <mesh name="Mesh507_1" geometry={nodes.Mesh507_1.geometry} material={nodes.Mesh507_1.material}/>
        </group>
        <group name="Sphere_cell080_cell097" position={[-0.6574, -0.3431, -0.7423]}>
          <mesh name="Mesh505" geometry={nodes.Mesh505.geometry} material={nodes.Mesh505.material}/>
          <mesh name="Mesh505_1" geometry={nodes.Mesh505_1.geometry} material={nodes.Mesh505_1.material}/>
        </group>
        <group name="Sphere_cell080_cell096" position={[-0.3863, -0.3028, -0.9424]}>
          <mesh name="Mesh504" geometry={nodes.Mesh504.geometry} material={nodes.Mesh504.material}/>
          <mesh name="Mesh504_1" geometry={nodes.Mesh504_1.geometry} material={nodes.Mesh504_1.material}/>
        </group>
        <group name="Sphere_cell080_cell095" position={[-0.4671, -0.3057, -0.881]}>
          <mesh name="Mesh503" geometry={nodes.Mesh503.geometry} material={nodes.Mesh503.material}/>
          <mesh name="Mesh503_1" geometry={nodes.Mesh503_1.geometry} material={nodes.Mesh503_1.material}/>
        </group>
        <group name="Sphere_cell080_cell094" position={[-0.6352, -0.2741, -0.7714]}>
          <mesh name="Mesh502" geometry={nodes.Mesh502.geometry} material={nodes.Mesh502.material}/>
          <mesh name="Mesh502_1" geometry={nodes.Mesh502_1.geometry} material={nodes.Mesh502_1.material}/>
        </group>
        <group name="Sphere_cell080_cell092" position={[-0.4419, -0.3766, -0.8801]}>
          <mesh name="Mesh500" geometry={nodes.Mesh500.geometry} material={nodes.Mesh500.material}/>
          <mesh name="Mesh500_1" geometry={nodes.Mesh500_1.geometry} material={nodes.Mesh500_1.material}/>
        </group>
        <group name="Sphere_cell080_cell090" position={[0.4681, -0.3024, 0.9111]}>
          <mesh name="Mesh498" geometry={nodes.Mesh498.geometry} material={nodes.Mesh498.material}/>
          <mesh name="Mesh498_1" geometry={nodes.Mesh498_1.geometry} material={nodes.Mesh498_1.material}/>
        </group>
        <group name="Sphere_cell080_cell088" position={[0.4686, -0.1674, 0.9183]}>
          <mesh name="Mesh496" geometry={nodes.Mesh496.geometry} material={nodes.Mesh496.material}/>
          <mesh name="Mesh496_1" geometry={nodes.Mesh496_1.geometry} material={nodes.Mesh496_1.material}/>
        </group>
        <group name="Sphere_cell080_cell087" position={[0.3861, -0.3302, 0.9354]}>
          <mesh name="Mesh495" geometry={nodes.Mesh495.geometry} material={nodes.Mesh495.material}/>
          <mesh name="Mesh495_1" geometry={nodes.Mesh495_1.geometry} material={nodes.Mesh495_1.material}/>
        </group>
        <group name="Sphere_cell080_cell086" position={[0.4188, -0.3153, 0.9178]}>
          <mesh name="Mesh494" geometry={nodes.Mesh494.geometry} material={nodes.Mesh494.material}/>
          <mesh name="Mesh494_1" geometry={nodes.Mesh494_1.geometry} material={nodes.Mesh494_1.material}/>
        </group>
        <group name="Sphere_cell080_cell084" position={[0.3324, 0.202, 0.9855]}>
          <mesh name="Mesh492" geometry={nodes.Mesh492.geometry} material={nodes.Mesh492.material}/>
          <mesh name="Mesh492_1" geometry={nodes.Mesh492_1.geometry} material={nodes.Mesh492_1.material}/>
        </group>
        <group name="Sphere_cell080_cell082" position={[0.4172, -0.1723, 0.9622]}>
          <mesh name="Mesh490" geometry={nodes.Mesh490.geometry} material={nodes.Mesh490.material}/>
          <mesh name="Mesh490_1" geometry={nodes.Mesh490_1.geometry} material={nodes.Mesh490_1.material}/>
        </group>
        <group name="Sphere_cell080_cell080" position={[0, -0.1225, 1.0497]}>
          <mesh name="Mesh488" geometry={nodes.Mesh488.geometry} material={nodes.Mesh488.material}/>
          <mesh name="Mesh488_1" geometry={nodes.Mesh488_1.geometry} material={nodes.Mesh488_1.material}/>
        </group>
        <group name="Sphere_cell080_cell077" position={[0.0824, -0.2922, 1.0102]}>
          <mesh name="Mesh485" geometry={nodes.Mesh485.geometry} material={nodes.Mesh485.material}/>
          <mesh name="Mesh485_1" geometry={nodes.Mesh485_1.geometry} material={nodes.Mesh485_1.material}/>
        </group>
        <group name="Sphere_cell080_cell075" position={[0.2598, -0.3709, 0.9559]}>
          <mesh name="Mesh483" geometry={nodes.Mesh483.geometry} material={nodes.Mesh483.material}/>
          <mesh name="Mesh483_1" geometry={nodes.Mesh483_1.geometry} material={nodes.Mesh483_1.material}/>
        </group>
        <group name="Sphere_cell080_cell074" position={[-0.0976, -0.1487, 1.0432]}>
          <mesh name="Mesh482" geometry={nodes.Mesh482.geometry} material={nodes.Mesh482.material}/>
          <mesh name="Mesh482_1" geometry={nodes.Mesh482_1.geometry} material={nodes.Mesh482_1.material}/>
        </group>
        <group name="Sphere_cell080_cell073" position={[0.2661, -0.2205, 1.0029]}>
          <mesh name="Mesh481" geometry={nodes.Mesh481.geometry} material={nodes.Mesh481.material}/>
          <mesh name="Mesh481_1" geometry={nodes.Mesh481_1.geometry} material={nodes.Mesh481_1.material}/>
        </group>
        <group name="Sphere_cell080_cell072" position={[0.3135, -0.3078, 0.9674]}>
          <mesh name="Mesh480" geometry={nodes.Mesh480.geometry} material={nodes.Mesh480.material}/>
          <mesh name="Mesh480_1" geometry={nodes.Mesh480_1.geometry} material={nodes.Mesh480_1.material}/>
        </group>
        <group name="Sphere_cell080_cell071" position={[0.2232, -0.1442, 1.0192]}>
          <mesh name="Mesh479" geometry={nodes.Mesh479.geometry} material={nodes.Mesh479.material}/>
          <mesh name="Mesh479_1" geometry={nodes.Mesh479_1.geometry} material={nodes.Mesh479_1.material}/>
        </group>
        <group name="Sphere_cell080_cell070" position={[0.9931, 0.2398, -0.2649]}>
          <mesh name="Mesh478" geometry={nodes.Mesh478.geometry} material={nodes.Mesh478.material}/>
          <mesh name="Mesh478_1" geometry={nodes.Mesh478_1.geometry} material={nodes.Mesh478_1.material}/>
        </group>
        <group name="Sphere_cell080_cell069" position={[0.8529, 0.2856, -0.541]}>
          <mesh name="Mesh477" geometry={nodes.Mesh477.geometry} material={nodes.Mesh477.material}/>
          <mesh name="Mesh477_1" geometry={nodes.Mesh477_1.geometry} material={nodes.Mesh477_1.material}/>
        </group>
        <group name="Sphere_cell080_cell066" position={[0.8358, 0.2294, -0.6116]}>
          <mesh name="Mesh474" geometry={nodes.Mesh474.geometry} material={nodes.Mesh474.material}/>
          <mesh name="Mesh474_1" geometry={nodes.Mesh474_1.geometry} material={nodes.Mesh474_1.material}/>
        </group>
        <group name="Sphere_cell080_cell065" position={[0.8926, 0.3087, -0.4811]}>
          <mesh name="Mesh473" geometry={nodes.Mesh473.geometry} material={nodes.Mesh473.material}/>
          <mesh name="Mesh473_1" geometry={nodes.Mesh473_1.geometry} material={nodes.Mesh473_1.material}/>
        </group>
        <group name="Sphere_cell080_cell064" position={[0.8753, 0.1502, -0.5724]}>
          <mesh name="Mesh472" geometry={nodes.Mesh472.geometry} material={nodes.Mesh472.material}/>
          <mesh name="Mesh472_1" geometry={nodes.Mesh472_1.geometry} material={nodes.Mesh472_1.material}/>
        </group>
        <group name="Sphere_cell080_cell063" position={[0.752, 0.251, -0.6989]}>
          <mesh name="Mesh471" geometry={nodes.Mesh471.geometry} material={nodes.Mesh471.material}/>
          <mesh name="Mesh471_1" geometry={nodes.Mesh471_1.geometry} material={nodes.Mesh471_1.material}/>
        </group>
        <group name="Sphere_cell080_cell062" position={[0.9349, 0.3244, -0.3767]}>
          <mesh name="Mesh470" geometry={nodes.Mesh470.geometry} material={nodes.Mesh470.material}/>
          <mesh name="Mesh470_1" geometry={nodes.Mesh470_1.geometry} material={nodes.Mesh470_1.material}/>
        </group>
        <group name="Sphere_cell080_cell061" position={[0.7421, 0.3309, -0.6749]}>
          <mesh name="Mesh469" geometry={nodes.Mesh469.geometry} material={nodes.Mesh469.material}/>
          <mesh name="Mesh469_1" geometry={nodes.Mesh469_1.geometry} material={nodes.Mesh469_1.material}/>
        </group>
        <group name="Sphere_cell080_cell060" position={[-0.9452, 0.398, -0.2586]}>
          <mesh name="Mesh468" geometry={nodes.Mesh468.geometry} material={nodes.Mesh468.material}/>
          <mesh name="Mesh468_1" geometry={nodes.Mesh468_1.geometry} material={nodes.Mesh468_1.material}/>
        </group>
        <group name="Sphere_cell080_cell058" position={[-0.7976, 0.1711, -0.6567]}>
          <mesh name="Mesh466" geometry={nodes.Mesh466.geometry} material={nodes.Mesh466.material}/>
          <mesh name="Mesh466_1" geometry={nodes.Mesh466_1.geometry} material={nodes.Mesh466_1.material}/>
        </group>
        <group name="Sphere_cell080_cell057" position={[-0.96, 0.2848, -0.3092]}>
          <mesh name="Mesh465" geometry={nodes.Mesh465.geometry} material={nodes.Mesh465.material}/>
          <mesh name="Mesh465_1" geometry={nodes.Mesh465_1.geometry} material={nodes.Mesh465_1.material}/>
        </group>
        <group name="Sphere_cell080_cell056" position={[-0.7637, 0.3819, -0.6127]}>
          <mesh name="Mesh464" geometry={nodes.Mesh464.geometry} material={nodes.Mesh464.material}/>
          <mesh name="Mesh464_1" geometry={nodes.Mesh464_1.geometry} material={nodes.Mesh464_1.material}/>
        </group>
        <group name="Sphere_cell080_cell053" position={[-0.8717, 0.317, -0.4802]}>
          <mesh name="Mesh461" geometry={nodes.Mesh461.geometry} material={nodes.Mesh461.material}/>
          <mesh name="Mesh461_1" geometry={nodes.Mesh461_1.geometry} material={nodes.Mesh461_1.material}/>
        </group>
        <group name="Sphere_cell080_cell052" position={[-0.9193, 0.4324, -0.2333]}>
          <mesh name="Mesh460" geometry={nodes.Mesh460.geometry} material={nodes.Mesh460.material}/>
          <mesh name="Mesh460_1" geometry={nodes.Mesh460_1.geometry} material={nodes.Mesh460_1.material}/>
        </group>
        <group name="Sphere_cell080_cell051" position={[-0.6983, 0.2738, -0.731]}>
          <mesh name="Mesh459" geometry={nodes.Mesh459.geometry} material={nodes.Mesh459.material}/>
          <mesh name="Mesh459_1" geometry={nodes.Mesh459_1.geometry} material={nodes.Mesh459_1.material}/>
        </group>
        <group name="Sphere_cell080_cell048" position={[-0.8255, -0.2408, -0.6006]}>
          <mesh name="Mesh456" geometry={nodes.Mesh456.geometry} material={nodes.Mesh456.material}/>
          <mesh name="Mesh456_1" geometry={nodes.Mesh456_1.geometry} material={nodes.Mesh456_1.material}/>
        </group>
        <group name="Sphere_cell080_cell041" position={[-0.7189, -0.2154, -0.735]}>
          <mesh name="Mesh449" geometry={nodes.Mesh449.geometry} material={nodes.Mesh449.material}/>
          <mesh name="Mesh449_1" geometry={nodes.Mesh449_1.geometry} material={nodes.Mesh449_1.material}/>
        </group>
        <group name="Sphere_cell080_cell037" position={[0.9715, -0.1913, 0.3969]}>
          <mesh name="Mesh445" geometry={nodes.Mesh445.geometry} material={nodes.Mesh445.material}/>
          <mesh name="Mesh445_1" geometry={nodes.Mesh445_1.geometry} material={nodes.Mesh445_1.material}/>
        </group>
        <group name="Sphere_cell080_cell036" position={[0.9826, 0.2104, 0.3228]}>
          <mesh name="Mesh444" geometry={nodes.Mesh444.geometry} material={nodes.Mesh444.material}/>
          <mesh name="Mesh444_1" geometry={nodes.Mesh444_1.geometry} material={nodes.Mesh444_1.material}/>
        </group>
        <group name="Sphere_cell080_cell033" position={[0.9788, -0.2647, 0.2947]}>
          <mesh name="Mesh441" geometry={nodes.Mesh441.geometry} material={nodes.Mesh441.material}/>
          <mesh name="Mesh441_1" geometry={nodes.Mesh441_1.geometry} material={nodes.Mesh441_1.material}/>
        </group>
        <group name="Sphere_cell080_cell032" position={[0.9547, -0.1278, 0.4821]}>
          <mesh name="Mesh440" geometry={nodes.Mesh440.geometry} material={nodes.Mesh440.material}/>
          <mesh name="Mesh440_1" geometry={nodes.Mesh440_1.geometry} material={nodes.Mesh440_1.material}/>
        </group>
        <group name="Sphere_cell080_cell030" position={[-0.9981, 0.177, -0.2805]}>
          <mesh name="Mesh438" geometry={nodes.Mesh438.geometry} material={nodes.Mesh438.material}/>
          <mesh name="Mesh438_1" geometry={nodes.Mesh438_1.geometry} material={nodes.Mesh438_1.material}/>
        </group>
        <group name="Sphere_cell080_cell026" position={[-0.986, 0.3641, -0.0835]}>
          <mesh name="Mesh434" geometry={nodes.Mesh434.geometry} material={nodes.Mesh434.material}/>
          <mesh name="Mesh434_1" geometry={nodes.Mesh434_1.geometry} material={nodes.Mesh434_1.material}/>
        </group>
        <group name="Sphere_cell080_cell025" position={[-0.9627, -0.1769, -0.3715]}>
          <mesh name="Mesh433" geometry={nodes.Mesh433.geometry} material={nodes.Mesh433.material}/>
          <mesh name="Mesh433_1" geometry={nodes.Mesh433_1.geometry} material={nodes.Mesh433_1.material}/>
        </group>
        <group name="Sphere_cell080_cell023" position={[-1.0149, 0.2864, -0.0487]}>
          <mesh name="Mesh431" geometry={nodes.Mesh431.geometry} material={nodes.Mesh431.material}/>
          <mesh name="Mesh431_1" geometry={nodes.Mesh431_1.geometry} material={nodes.Mesh431_1.material}/>
        </group>
        <group name="Sphere_cell080_cell022" position={[-0.9972, 0.2512, -0.1837]}>
          <mesh name="Mesh430" geometry={nodes.Mesh430.geometry} material={nodes.Mesh430.material}/>
          <mesh name="Mesh430_1" geometry={nodes.Mesh430_1.geometry} material={nodes.Mesh430_1.material}/>
        </group>
        <group name="Sphere_cell080_cell021" position={[-0.8921, -0.2167, -0.5062]}>
          <mesh name="Mesh429" geometry={nodes.Mesh429.geometry} material={nodes.Mesh429.material}/>
          <mesh name="Mesh429_1" geometry={nodes.Mesh429_1.geometry} material={nodes.Mesh429_1.material}/>
        </group>
        <group name="Sphere_cell080_cell020" position={[1.0232, -0.2082, -0.1469]}>
          <mesh name="Mesh428" geometry={nodes.Mesh428.geometry} material={nodes.Mesh428.material}/>
          <mesh name="Mesh428_1" geometry={nodes.Mesh428_1.geometry} material={nodes.Mesh428_1.material}/>
        </group>
        <group name="Sphere_cell080_cell017" position={[0.9015, -0.4744, -0.2777]}>
          <mesh name="Mesh425" geometry={nodes.Mesh425.geometry} material={nodes.Mesh425.material}/>
          <mesh name="Mesh425_1" geometry={nodes.Mesh425_1.geometry} material={nodes.Mesh425_1.material}/>
        </group>
        <group name="Sphere_cell080_cell016" position={[0.9548, -0.2716, -0.3579]}>
          <mesh name="Mesh424" geometry={nodes.Mesh424.geometry} material={nodes.Mesh424.material}/>
          <mesh name="Mesh424_1" geometry={nodes.Mesh424_1.geometry} material={nodes.Mesh424_1.material}/>
        </group>
        <group name="Sphere_cell080_cell012" position={[0.9612, -0.4191, -0.0435]}>
          <mesh name="Mesh420" geometry={nodes.Mesh420.geometry} material={nodes.Mesh420.material}/>
          <mesh name="Mesh420_1" geometry={nodes.Mesh420_1.geometry} material={nodes.Mesh420_1.material}/>
        </group>
        <group name="Sphere_cell080_cell011" position={[0.9886, -0.1029, -0.363]}>
          <mesh name="Mesh419" geometry={nodes.Mesh419.geometry} material={nodes.Mesh419.material}/>
          <mesh name="Mesh419_1" geometry={nodes.Mesh419_1.geometry} material={nodes.Mesh419_1.material}/>
        </group>
        <group name="Sphere_cell080_cell009" position={[0.6161, -0.1932, -0.8385]}>
          <mesh name="Mesh417" geometry={nodes.Mesh417.geometry} material={nodes.Mesh417.material}/>
          <mesh name="Mesh417_1" geometry={nodes.Mesh417_1.geometry} material={nodes.Mesh417_1.material}/>
        </group>
        <group name="Sphere_cell080_cell008" position={[0.8953, -0.1626, -0.5233]}>
          <mesh name="Mesh416" geometry={nodes.Mesh416.geometry} material={nodes.Mesh416.material}/>
          <mesh name="Mesh416_1" geometry={nodes.Mesh416_1.geometry} material={nodes.Mesh416_1.material}/>
        </group>
        <group name="Sphere_cell080_cell007" position={[0.7367, -0.2403, -0.7156]}>
          <mesh name="Mesh415" geometry={nodes.Mesh415.geometry} material={nodes.Mesh415.material}/>
          <mesh name="Mesh415_1" geometry={nodes.Mesh415_1.geometry} material={nodes.Mesh415_1.material}/>
        </group>
        <group name="Sphere_cell080_cell005" position={[0.8967, -0.3282, -0.4759]}>
          <mesh name="Mesh414" geometry={nodes.Mesh414.geometry} material={nodes.Mesh414.material}/>
          <mesh name="Mesh414_1" geometry={nodes.Mesh414_1.geometry} material={nodes.Mesh414_1.material}/>
        </group>
        <group name="Sphere_cell080_cell001" position={[0.8739, -0.2898, -0.5233]}>
          <mesh name="Mesh410" geometry={nodes.Mesh410.geometry} material={nodes.Mesh410.material}/>
          <mesh name="Mesh410_1" geometry={nodes.Mesh410_1.geometry} material={nodes.Mesh410_1.material}/>
        </group>
        <group name="Sphere_cell080_cell000" position={[0.8057, -0.2119, -0.657]}>
          <mesh name="Mesh409" geometry={nodes.Mesh409.geometry} material={nodes.Mesh409.material}/>
          <mesh name="Mesh409_1" geometry={nodes.Mesh409_1.geometry} material={nodes.Mesh409_1.material}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
