/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useEffect, useRef, useState} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three/examples/jsm/loaders/GLTFLoader'
import {useStore} from "@/utils/store";

type GLTFResult = GLTF & {
  nodes: {
    Ethereum: THREE.Mesh
  }
  materials: {
    ['(null)']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://dqeczc7c9n9n1.cloudfront.net/models/eth-1663535083/eth.glb.gz";

export default function Model(props: { color: string } & JSX.IntrinsicElements['group']) {
  const {color} = props;
  const group = useRef<THREE.Group>();
  
  const {objectQueued, objectRendered} = useStore(state => ({
    objectQueued: state.objectQueued,
    objectRendered: state.objectRendered
  }))
  objectQueued("eth");
  
  const {nodes, materials} = useGLTF(FILE_URL) as GLTFResult
  
  useEffect(() => {
    
    objectRendered("eth")
    
  }, [nodes]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position-y={2}>
        <mesh
          name="Ethereum"
          geometry={nodes.Ethereum.geometry}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <meshStandardMaterial color={color}/>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
