/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: shiningdust (https://sketchfab.com/shiningdust)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/headphones-883e01b9e4c9463db89e9d643be6778c
title: headphones
*/

import * as THREE from 'three'
import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ring_fabric_0: THREE.Mesh
    ring_leather_0: THREE.Mesh
    hinge_plastic_0: THREE.Mesh
    hp_i_leather_0: THREE.Mesh
    hp_i_fabric_0: THREE.Mesh
    hp_plastic_0: THREE.Mesh
    hp_plastic_mirror_0: THREE.Mesh
    hp_metal_0: THREE.Mesh
    buttons_buttons_0: THREE.Mesh
    wire_r_wires_0: THREE.Mesh
    wire_l_wires_0: THREE.Mesh
  }
  materials: {
    fabric: THREE.MeshStandardMaterial
    leather: THREE.MeshStandardMaterial
    plastic: THREE.MeshStandardMaterial
    plastic_mirror: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    buttons: THREE.MeshStandardMaterial
    wires: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://dqeczc7c9n9n1.cloudfront.net/models/headphones-1663535247/headphones.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const {nodes, materials} = useGLTF(FILE_URL) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="570b8c383a9c405b90cd697f5c8a6f66fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="ring" rotation={[-Math.PI / 2, 0, 0]} scale={9.0625}>
                <mesh
                  name="ring_fabric_0"
                  geometry={nodes.ring_fabric_0.geometry}
                  material={nodes.ring_fabric_0.material}
                />
                <mesh
                  name="ring_leather_0"
                  geometry={nodes.ring_leather_0.geometry}
                  material={nodes.ring_leather_0.material}
                />
              </group>
              <group name="hinge" rotation={[-1.5585, -0.3032, 0.0104]} scale={[9.0625, 9.0625, 9.0625]}>
                <mesh
                  name="hinge_plastic_0"
                  geometry={nodes.hinge_plastic_0.geometry}
                  material={nodes.hinge_plastic_0.material}
                />
              </group>
              <group name="hp" rotation={[Math.PI / 2, -1.1289, -Math.PI]} scale={[9.0625, 9.0625, 9.0625]}>
                <group name="hp_i">
                  <mesh
                    name="hp_i_leather_0"
                    geometry={nodes.hp_i_leather_0.geometry}
                    material={nodes.hp_i_leather_0.material}
                  />
                  <mesh
                    name="hp_i_fabric_0"
                    geometry={nodes.hp_i_fabric_0.geometry}
                    material={nodes.hp_i_fabric_0.material}
                  />
                </group>
                <mesh
                  name="hp_plastic_0"
                  geometry={nodes.hp_plastic_0.geometry}
                  material={nodes.hp_plastic_0.material}
                />
                <mesh
                  name="hp_plastic_mirror_0"
                  geometry={nodes.hp_plastic_mirror_0.geometry}
                  material={materials.plastic_mirror}
                />
                <mesh name="hp_metal_0" geometry={nodes.hp_metal_0.geometry} material={materials.metal}/>
              </group>
              <group name="buttons" rotation={[Math.PI / 2, -1.1289, -Math.PI]} scale={[9.0625, 9.0625, 9.0625]}>
                <mesh
                  name="buttons_buttons_0"
                  geometry={nodes.buttons_buttons_0.geometry}
                  material={materials.buttons}
                />
              </group>
              <group name="wire_r" rotation={[-Math.PI / 2, 0, 0]} scale={9.0625}>
                <mesh
                  name="wire_r_wires_0"
                  geometry={nodes.wire_r_wires_0.geometry}
                  material={nodes.wire_r_wires_0.material}
                />
              </group>
              <group name="wire_l" rotation={[-Math.PI / 2, 0, 0]} scale={9.0625}>
                <mesh
                  name="wire_l_wires_0"
                  geometry={nodes.wire_l_wires_0.geometry}
                  material={nodes.wire_l_wires_0.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
