/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		CPDeLorean_EngineFrontL: THREE.Mesh;
		CPDeLorean_EngineFrontL001: THREE.Mesh;
		CPDeLorean_EngineFrontL002: THREE.Mesh;
		Mesh008: THREE.Mesh;
		Mesh008_1: THREE.Mesh;
		Mesh008_2: THREE.Mesh;
		CPDeLorean_EngineFrontR: THREE.Mesh;
		CPDeLorean_EngineFrontR001: THREE.Mesh;
		CPDeLorean_EngineFrontR002: THREE.Mesh;
		Mesh009: THREE.Mesh;
		Mesh009_1: THREE.Mesh;
		Mesh009_2: THREE.Mesh;
		CPDeLorean_EngineRearL: THREE.Mesh;
		CPDeLorean_EngineRearL001: THREE.Mesh;
		CPDeLorean_EngineRearL002: THREE.Mesh;
		CPDeLorean_EngineRearL_pipes: THREE.Mesh;
		CPDeLorean_EngineRearR: THREE.Mesh;
		CPDeLorean_EngineRearR001: THREE.Mesh;
		CPDeLorean_EngineRearR002: THREE.Mesh;
		CPDeLorean_EngineRearR_pipes: THREE.Mesh;
		CPDeLorean_MainBody001: THREE.Mesh;
		CPDeLorean_MainBody003: THREE.Mesh;
		CPDeLorean_MainBody004: THREE.Mesh;
		CPDeLorean_MainBody005: THREE.Mesh;
		CPDeLorean_MainBody006: THREE.Mesh;
		CPDeLorean_MainBody007: THREE.Mesh;
		CPDeLorean_MainBody008: THREE.Mesh;
		CPDeLorean_MainBody009: THREE.Mesh;
		Mesh003: THREE.Mesh;
		Mesh003_1: THREE.Mesh;
		Mesh003_2: THREE.Mesh;
		CPDeLorean_MainBody002: THREE.Mesh;
		CPDeLorean_MainBody011: THREE.Mesh;
		CPDeLorean_WingDx: THREE.Mesh;
		CPDeLorean_WingSx: THREE.Mesh;
	};
	materials: {
		DeLorean_EnginePart2: THREE.MeshStandardMaterial;
		DeLorean_EnginePart1: THREE.MeshStandardMaterial;
		DeLorean_EnginePart3: THREE.MeshStandardMaterial;
		DeLorean_Motore: THREE.MeshStandardMaterial;
		DeLorean_DarkCables: THREE.MeshStandardMaterial;
		DeLorean_BlueLight: THREE.MeshStandardMaterial;
		Standard_8: THREE.MeshStandardMaterial;
		DeLorean_WhiteLight: THREE.MeshStandardMaterial;
		DeLorean_Interni: THREE.MeshStandardMaterial;
		DeLorean_FinituraNero: THREE.MeshStandardMaterial;
		DeLorean_OrangeLight: THREE.MeshStandardMaterial;
		DeLorean_RedLight: THREE.MeshStandardMaterial;
		DeLorean_BrightCables: THREE.MeshStandardMaterial;
		DeLorean_MainBody: THREE.MeshStandardMaterial;
	};
};

const FILE_URL = "https://dqeczc7c9n9n1.cloudfront.net/models/dolorean6-1659492342/dolorean6.glb.gz";
type ActionName = "Action.003";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Car( props: JSX.IntrinsicElements["group"] ) {

	const group = useRef<THREE.Group>( null );
	const { nodes, materials, animations } = useGLTF( FILE_URL ) as GLTFResult;
	const actions = useAnimations<any>( animations, group );
	console.log( actions );

	return (
		<group ref={group} scale={0.5} position={[ - 0.1, 0.075, 0.1 ]} rotation-x={Math.PI / 12} {...props} dispose={null}>
			<group name="Scene">
				{/*<group*/}
				{/*	name="NurbsCircle"*/}
				{/*	position={[ 0.8, 1.6, 6.1 ]}*/}
				{/*	rotation={[ - 0.2, - 0.1, 0.1 ]}*/}
				{/*	scale={[ 11.9, 9.8, 6.2 ]}*/}
				{/*/>*/}
				<group name="Empty" position={[ - 0.1, 0, 0 ]} rotation={[ - 1.9, 1.5, 1.6 ]}>
					<group
						name="CPDeLorean_MainBody"
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineFrontL"
						geometry={nodes.CPDeLorean_EngineFrontL.geometry}
						material={materials.DeLorean_EnginePart2}
						position={[ 0.5, - 0.3, 1.4 ]}
						rotation={[ Math.PI / 2, - 0.4, - Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineFrontL001"
						geometry={nodes.CPDeLorean_EngineFrontL001.geometry}
						material={materials.DeLorean_EnginePart1}
						position={[ 0.5, - 0.3, 1.4 ]}
						rotation={[ Math.PI / 2, - 0.4, - Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineFrontL002"
						geometry={nodes.CPDeLorean_EngineFrontL002.geometry}
						material={materials.DeLorean_EnginePart3}
						position={[ 0.5, - 0.3, 1.4 ]}
						rotation={[ Math.PI / 2, - 0.4, - Math.PI / 2 ]}
						scale={0}
					/>
					<group
						name="CPDeLorean_EngineFrontL_pipes"
						position={[ 0.4, 0.1, 1.4 ]}
						rotation={[ - 1.5, 0, Math.PI / 2 ]}
						scale={0}
					>
						<mesh
							name="Mesh008"
							geometry={nodes.Mesh008.geometry}
							material={materials.DeLorean_Motore}
						/>
						<mesh
							name="Mesh008_1"
							geometry={nodes.Mesh008_1.geometry}
							material={materials.DeLorean_EnginePart3}
						/>
						<mesh
							name="Mesh008_2"
							geometry={nodes.Mesh008_2.geometry}
							material={materials.DeLorean_DarkCables}
						/>
					</group>
					<mesh
						name="CPDeLorean_EngineFrontR"
						geometry={nodes.CPDeLorean_EngineFrontR.geometry}
						material={materials.DeLorean_EnginePart2}
						position={[ - 0.6, - 0.3, 1.4 ]}
						rotation={[ - Math.PI / 2, - 0.4, Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineFrontR001"
						geometry={nodes.CPDeLorean_EngineFrontR001.geometry}
						material={materials.DeLorean_EnginePart1}
						position={[ - 0.6, - 0.3, 1.4 ]}
						rotation={[ - Math.PI / 2, - 0.4, Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineFrontR002"
						geometry={nodes.CPDeLorean_EngineFrontR002.geometry}
						material={materials.DeLorean_EnginePart3}
						position={[ - 0.6, - 0.3, 1.4 ]}
						rotation={[ - Math.PI / 2, - 0.4, Math.PI / 2 ]}
						scale={0}
					/>
					<group
						name="CPDeLorean_EngineFrontR_pipes"
						position={[ - 0.4, 0.1, 1.4 ]}
						rotation={[ 1.7, 0, Math.PI / 2 ]}
						scale={0}
					>
						<mesh
							name="Mesh009"
							geometry={nodes.Mesh009.geometry}
							material={materials.DeLorean_Motore}
						/>
						<mesh
							name="Mesh009_1"
							geometry={nodes.Mesh009_1.geometry}
							material={materials.DeLorean_EnginePart3}
						/>
						<mesh
							name="Mesh009_2"
							geometry={nodes.Mesh009_2.geometry}
							material={materials.DeLorean_DarkCables}
						/>
					</group>
					<mesh
						name="CPDeLorean_EngineRearL"
						geometry={nodes.CPDeLorean_EngineRearL.geometry}
						material={materials.DeLorean_EnginePart2}
						position={[ 0.5, - 0.3, - 0.4 ]}
						rotation={[ Math.PI / 2, - 0.4, - Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineRearL001"
						geometry={nodes.CPDeLorean_EngineRearL001.geometry}
						material={materials.DeLorean_EnginePart1}
						position={[ 0.5, - 0.3, - 0.4 ]}
						rotation={[ Math.PI / 2, - 0.4, - Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineRearL002"
						geometry={nodes.CPDeLorean_EngineRearL002.geometry}
						material={materials.DeLorean_EnginePart3}
						position={[ 0.5, - 0.3, - 0.4 ]}
						rotation={[ Math.PI / 2, - 0.4, - Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineRearL_pipes"
						geometry={nodes.CPDeLorean_EngineRearL_pipes.geometry}
						material={materials.DeLorean_DarkCables}
						position={[ 0.6, - 0.1, - 0.6 ]}
						rotation={[ 0.9, 0.9, - Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineRearR"
						geometry={nodes.CPDeLorean_EngineRearR.geometry}
						material={materials.DeLorean_EnginePart2}
						position={[ - 0.6, - 0.3, - 0.4 ]}
						rotation={[ - Math.PI / 2, - 0.4, Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineRearR001"
						geometry={nodes.CPDeLorean_EngineRearR001.geometry}
						material={materials.DeLorean_EnginePart1}
						position={[ - 0.6, - 0.3, - 0.4 ]}
						rotation={[ - Math.PI / 2, - 0.4, Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineRearR002"
						geometry={nodes.CPDeLorean_EngineRearR002.geometry}
						material={materials.DeLorean_EnginePart3}
						position={[ - 0.6, - 0.3, - 0.4 ]}
						rotation={[ - Math.PI / 2, - 0.4, Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_EngineRearR_pipes"
						geometry={nodes.CPDeLorean_EngineRearR_pipes.geometry}
						material={materials.DeLorean_DarkCables}
						position={[ - 0.7, - 0.1, - 0.6 ]}
						rotation={[ - 2.3, 0.9, - Math.PI / 2 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody001"
						geometry={nodes.CPDeLorean_MainBody001.geometry}
						material={materials.DeLorean_BlueLight}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody003"
						geometry={nodes.CPDeLorean_MainBody003.geometry}
						material={materials.DeLorean_Motore}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody004"
						geometry={nodes.CPDeLorean_MainBody004.geometry}
						material={materials.Standard_8}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody005"
						geometry={nodes.CPDeLorean_MainBody005.geometry}
						material={materials.DeLorean_WhiteLight}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody006"
						geometry={nodes.CPDeLorean_MainBody006.geometry}
						material={materials.DeLorean_Interni}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody007"
						geometry={nodes.CPDeLorean_MainBody007.geometry}
						material={materials.DeLorean_FinituraNero}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody008"
						geometry={nodes.CPDeLorean_MainBody008.geometry}
						material={materials.DeLorean_OrangeLight}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody009"
						geometry={nodes.CPDeLorean_MainBody009.geometry}
						material={materials.DeLorean_RedLight}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<group
						name="CPDeLorean_RoofTopDevice"
						position={[ 0, 0.4, - 0.2 ]}
						rotation={[ - 1.7, 0, 0 ]}
						scale={0}
					>
						<mesh
							name="Mesh003"
							geometry={nodes.Mesh003.geometry}
							material={materials.DeLorean_Motore}
						/>
						<mesh
							name="Mesh003_1"
							geometry={nodes.Mesh003_1.geometry}
							material={materials.DeLorean_BrightCables}
						/>
						<mesh
							name="Mesh003_2"
							geometry={nodes.Mesh003_2.geometry}
							material={materials.DeLorean_DarkCables}
						/>
					</group>
					<mesh
						name="CPDeLorean_MainBody002"
						geometry={nodes.CPDeLorean_MainBody002.geometry}
						material={materials.DeLorean_MainBody}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_MainBody011"
						geometry={nodes.CPDeLorean_MainBody011.geometry}
						material={materials.DeLorean_MainBody}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_WingDx"
						geometry={nodes.CPDeLorean_WingDx.geometry}
						material={materials.DeLorean_MainBody}
						position={[ 0, - 0.5, 0.4 ]}
						rotation={[ Math.PI, 0, 0 ]}
						scale={0}
					/>
					<mesh
						name="CPDeLorean_WingSx"
						geometry={nodes.CPDeLorean_WingSx.geometry}
						material={materials.DeLorean_MainBody}
						position={[ 0, - 0.5, 0.4 ]}
						scale={0}
					/>
				</group>
			</group>
		</group>
	);

}

useGLTF.preload( FILE_URL );
