/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {ForwardedRef, MutableRefObject, useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Concrete_3_Mesh315_1: THREE.Mesh
    Concrete_3_Mesh315_2: THREE.Mesh
    Concrete_3_Mesh315_3: THREE.Mesh
    Concrete_3_Mesh315_4: THREE.Mesh
    Light_49_Mesh391_1: THREE.Mesh
    Light_49_Mesh391_2: THREE.Mesh
    Light_49_Mesh391_3: THREE.Mesh
    Light_49_Mesh391_4: THREE.Mesh
    Light_49_Mesh391_5: THREE.Mesh
  }
  materials: {
    NewWall: THREE.MeshStandardMaterial
    ['Mat.018']: THREE.MeshStandardMaterial
    street_light: THREE.MeshStandardMaterial
    ['NewWall.001']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://dqeczc7c9n9n1.cloudfront.net/models/newroad-1663385484/newroad.glb.gz";

// eslint-disable-next-line react/display-name
const Model = React.forwardRef((props: { ref1: MutableRefObject<THREE.Group>, ref2: MutableRefObject<THREE.Group> } & JSX.IntrinsicElements['group'], refs: any) => {
  
  // console.log(ref)
  const {ref1, ref2} = props;
  console.log(ref2)
  const group = useRef<THREE.Group>()
  const {nodes, materials} = useGLTF(FILE_URL) as GLTFResult
  
  return (
    <group ref={group} rotation-y={Math.PI / 2} position={[0, 0, -1.5]} {...props} dispose={null}>
      <group name="Scene">
        <directionalLight
          color="white"
          intensity={0.5}
          name="Sun"
          position={[288.3996, 320.9216, 126.2625]}
          target={new THREE.Object3D()}
          castShadow
        />
        {/* overhead bars */}
        <group ref={ref1} position-z={377.5}>
          <group position-z={250}>
            <group
              name="Concrete_3_Mesh315"
              position={[-16.1975, -0.0555, -254.2842]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.165}
            >
              <mesh
                name="Concrete_3_Mesh315_1"
                geometry={nodes.Concrete_3_Mesh315_1.geometry}
                material={nodes.Concrete_3_Mesh315_1.material}
                castSHadow
                receiveShadow
              />
              <mesh
                name="Concrete_3_Mesh315_2"
                geometry={nodes.Concrete_3_Mesh315_2.geometry}
                material={nodes.Concrete_3_Mesh315_2.material}
                castSHadow
                receiveShadow
              />
              <mesh
                name="Concrete_3_Mesh315_3"
                geometry={nodes.Concrete_3_Mesh315_3.geometry}
                material={nodes.Concrete_3_Mesh315_3.material}
                castSHadow
                receiveShadow
              />
              <mesh
                name="Concrete_3_Mesh315_4"
                geometry={nodes.Concrete_3_Mesh315_4.geometry}
                material={nodes.Concrete_3_Mesh315_4.material}
                castSHadow
                receiveShadow
              />
            </group>
          </group>
        </group>
        {/* no bars */}
        <group ref={ref2} position-z={162.5}>
          <group
            name="Light_49_Mesh391"
            position={[-0.0823, -0.0555, -254.2842]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.165}
          >
            <mesh
              name="Light_49_Mesh391_1"
              geometry={nodes.Light_49_Mesh391_1.geometry}
              material={nodes.Light_49_Mesh391_1.material}
            />
            <mesh
              name="Light_49_Mesh391_2"
              geometry={nodes.Light_49_Mesh391_2.geometry}
              material={nodes.Light_49_Mesh391_2.material}
            />
            <mesh
              name="Light_49_Mesh391_3"
              geometry={nodes.Light_49_Mesh391_3.geometry}
              material={nodes.Light_49_Mesh391_3.material}
            />
            <mesh
              name="Light_49_Mesh391_4"
              geometry={nodes.Light_49_Mesh391_4.geometry}
              material={materials['NewWall.001']}
            />
            <mesh
              name="Light_49_Mesh391_5"
              geometry={nodes.Light_49_Mesh391_5.geometry}
              material={nodes.Light_49_Mesh391_5.material}
              castShadow={true}
              receiveShadow
            />
          </group>
        </group>
      </group>
    </group>
  )
});

useGLTF.preload(FILE_URL)
export default Model
